### ISSUE TITLE
New Command Palette "Jump to Error"

### ISSUE THREAD

**Issue by Saevon** [SublimeLinter/SublimeLinter#1035]
The new panel is nice, acting similar to other editors by showing you the errors all the time. BUT I usually used the command to jump to a specific error easier.  Now I can't use the arrow keys (or other shortcuts) to jump around the errors on the file I have to click on each one to jump to it.

I would like the old version back, but as a more relevant command "Jump to Error" which would list the errors in the current file, and let you jump to one of them.

**Comment by braver** [comment]
> Now I can't use the arrow keys (or other shortcuts) to jump around the errors on the file I have to click on each one to jump to it.

Also, the panel can be navigated using the next_result and previous_result commands, just like any other panel. You can also use our own goto commands. 

The old quick panel with the list of errors was really annoying because:

- It looks like it already moves you to the error, but if you close the panel (ie. not press return) you're back where you started.
- You continuously have to start over from the first error if you want to go somewhere else.

The old UI will not return. The panel is different, but far superior.

**Comment by kaste** [comment]
> You can also navigate the panel by keyboard and jump to the line with the caret using return. It won't live preview the error though.

This doesn't work on our panel.

**Comment by jfcherng** [comment]
Keyboard navigation on the panel is not working for me, either.

**Comment by braver** [comment]
The interaction @FichteFoll describes doesn't exist as far as I know. You probably already have keybindings for the next_result and prev_result commands.

**Comment by Saevon** [comment]
@braver: yes, I have keybindings for the `next_result` and `prev_result` commands, but I don't believe (can't check right now) that they work with the new panel.

As a Vim-Mode user I dislike needing to use the mouse to move around the error list. Using the keyboard (up/down keys, and my other shortcuts) to move around lets me see the overall linting state better (by jumping around errors& their context quickly) AND let me stop at the solvable ones easily.
Essentially my focus would be on the panel, the **one line** of code the error is about and the **error message** all of which are in one place, BUT with the ability to move around it easier.
A Solution of using "next_error" and "prev_error" commands wouldn't really let me do that as the information would be spread out (status bar/panel + current line)


Looking at your points about the old panel, they're all quite true, but:

1. Not pressing return is actually consistent, e.g. the file panel won't jump you to a file unless you press enter... This lets me cancel the "jump to error" if I look over the existing ones and decide I can't fix them right now. Then I'm back exactly where I was before
2. Starting over does suck... if it could jump you to a closest error instead (not sure if sublime plugins can do that...) that would fix it.
3. Somewhat more rarely it let me filter the errors. E.g. grab all the import errors, or whitespace errors. Essentially letting me survey other people's code for pair-programming interactions, commenting on specific trends and such. (However this isn't a feature that this issue is about)


P.S. I'm not saying we should remove the new panel, I do like the alternative workflow it provides. BUT it isn't purely superior, clearly removing a useful workflow for me (while still adding a different one)

**Comment by braver** [comment]
> but I don't believe (can't check right now) that they work with the new panel.

They definitely do. You may need to focus the panel first though (same thing with all panels that these command operate on).

I can see how the old quick panel solution let's you do some things that are handy, but it has several UX issues that we cannot solve because the quick panel wasn't actually meant to do those things. It's designed to find and run commands, perhaps with some parameters. That's a bad fit to working through lists of errors, which is what this plugin is about. 

We made several really rigorous changes and I'm sure they're not all 100% better than what the old plugin provided. I am however also sure it's an overall win and we couldn't have gotten there without dropping a lot of the old stuff. I don't want this plugin to provide 10 ways to basically do the same thing, because of course thousands of users can come up with with work flows and use cases that will be optimally supported if we "just did it like this". A lot of what made SL3 such a terrible plugin was that it would fight and abuse API's and UI elements to super-optimise very specific work flows. SL4 does things a lot more like SublimeText was meant to be used, which makes live easier for everyone, except for those who were served by those "hacks". 

So, all of that to say that I do understand that SL4 isn't 100% better for everyone, but that the trade-offs were necessary and in the end benefit all users and maintainers. If we can find ways to improve SL4 for use cases we should do so, but within the confines of what makes sense given the ST API and UI. 
So, we shouldn't frame issues from a "I want this feature back" point of view, but start over from scratch and try to understand the use case.

**Comment by kaste** [comment]
FWIW you *should* navigate using these commands

https://github.com/SublimeLinter/SublimeLinter/blob/8cde70d14714a8a2e1ec33056d31ce867e2dd2e4/keymaps/Default%20(Linux).sublime-keymap#L25-L36

Then, the new panel supports filtering. (Now, we're on v4.0.0, so this is not the last version. 🆗 )

**Comment by Saevon** [comment]
@braver thanks for sharing your reasoning, that clarifies some things
@kaste I'll give the shortcuts a try, (see if `next_result` `prev_result` work fine for me as well)
 Also what do you mean "Then, the new panel supports filtering" is that a hint at features to come? (that would be cool)

**Comment by kaste** [comment]
I thought you mean something like this (but honestly we get a lot of issues today 😄 

https://github.com/SublimeLinter/SublimeLinter/blob/8cde70d14714a8a2e1ec33056d31ce867e2dd2e4/keymaps/Default%20(Linux).sublime-keymap#L6-L18

**Comment by braver** [comment]
@Saevon the filtering is already available. If you open the keybindings settings, the default file on the left has all the info you need to create keybindings that open the panel with filtering.

**Comment by FichteFoll** [comment]
(Yes, it appears I was confusing things.)
