### ISSUE TITLE
`ignore_match` no longer supported?

### ISSUE THREAD

**Issue by alecthomas** [SublimeLinter/SublimeLinter#1062]
Is that correct? What's the alternative for users now?

Each linter could reimplement this support, but that seems pretty redundant.

**Comment by kaste** [comment]
It was already gone as I joined here. But I looked at a lot of linter since, and frankly, nobody used it. `split_match` can return `None` to skip a match. Otherwise, `find_errors` operates on the raw output. Most just return None in `split_match`.

**Comment by alecthomas** [comment]
It was working prior to migrating to version 4.

It's a user configurable setting, not a setting that the linter controls. Users set it in their SublimeLinter config and SublimeLinter would exclude matches from the linter output automatically.

eg. Here is my clang configuration:

```
    "clang": {
      "@disable": false,
      "args": [],
      "excludes": [],
      "extra_flags": "-std=c++14 -stdlib=libc++",
      "ignore_match": [
        "#pragma once in main file",
        "unused variable '_'"
      ],
    },

```

**Comment by braver** [comment]
Yes, ignore_match is gone. SublimeLinter 3 would hide errors that match a certain pattern. It’s usually better to hide errors using the linter’s own configuration. E.g. via config files, or by passing args to the linter process to ignore certain rules. All this can be achieved using existing configuration. 

In addition, there are new features that allow you to filter error codes from the output panel, or to style them so that they’re easier to ignore.

Perhaps your linter lacks configuration features and ignore_match provided a stopgap. Most linters have become pretty mature in the 5+ years since most of SL3 was designed, so this would be an exception by now. Solving that in the UI of an editor seems like a terrible compromise to me.

So, this feature will not return, also not in linter plugins. If there is some use case we don’t understand we can discuss that and find out how to improve SL4 for it.

**Comment by braver** [comment]
Ok, we need new issues with good cases to get a move on this one.
