### ISSUE TITLE
Disable error popup when no linter available

### ISSUE THREAD

**Issue by it6** [SublimeLinter/SublimeLinter#1064]
How to hide console popup when there is no linter, there are many times where I work on a files which doesn't belong to any project and I don't want to setup linting.

With the new plugin I see a popup error message every time I save the file. I would like to hide the popup is there any setting for this? 

Please consider not showing popup when there is no linter available (just like in the old version) instead of obtrusive console popup.

<img width="872" alt="screen shot 2018-03-02 at 8 01 40 pm" src="https://user-images.githubusercontent.com/5510191/36928603-3a3028c4-1e55-11e8-9d3e-da2b4e7d9605.png">

this is the actual error

```
SublimeLinter: #6 eslint test.js ERROR:

 
Oops! Something went wrong! :(

ESLint: 4.18.1.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /Users/kotamrs/Desktop and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

**Comment by braver** [comment]
Currently eslint crashes inelegantly when there is no config file. The eslint plugin shouldn’t do that.

**Comment by kaste** [comment]
We could tackle this in the error handler, so that it shows identical messages at most once/every ten minutes etc.

**Comment by braver** [comment]
For eslint specifically, the absence of a config file means you don't want to lint. So, instead of crashing, it should basically say `can_lint = False` and be done with it.

Now, the next problem is that perhaps you *do* want to lint but didn't know that you didn't have a config file set up. We need to message that to the user. In old versions, it would show a warning at line 1, col 1 that said "no config file found". I think that's a reasonable solution and at least it's less intrusive than crashing and showing the message panel.

So, we could improve the error handler, but I think the way to go for this particular case is to improve how the eslint plugin deals with this situation.

**Comment by kaste** [comment]
> For eslint specifically, the absence of a config file means you don't want to lint.

I don't think so.

Generally to show the message panel is an improvement bc eslint has really nice and long messages here whenever you screw your config.

Did you know the `disable_if_not_dependency` setting? It tells NodeLinter to not use a global eslint.

**Comment by braver** [comment]
> Did you know the disable_if_not_dependency setting?

Nope, that's new for me.

I have globally installed eslint because I want to lint most of my Javascript projects. Almost none of those projects use node or npm in any way, they're just little website. If I want to lint them I put a config file in them. Where you install eslint and if you have a config file for it are completely separate things.

eslint doesn't work if you don't set it up. Therefore, if it has not been set up we should assume that's intentional and that the user doesn't want to lint.

**Comment by it6** [comment]
> For eslint specifically, the absence of a config file means you don't want to lint. So, instead of crashing, it should basically say can_lint = False and be done with it.

>Now, the next problem is that perhaps you do want to lint but didn't know that you didn't have a config file set up. We need to message that to the user. In old versions, it would show a warning at line 1, col 1 that said "no config file found". I think that's a reasonable solution and at least it's less intrusive than crashing and showing the message panel.

>So, we could improve the error handler, but I think the way to go for this particular case is to improve how the eslint plugin deals with this situation.

This solution would be great and cover all usages.

**Comment by kaste** [comment]
Now, we need to come back to normal reasoning.

I will not return a lint error or warning here bc the views and third party plugins (my own lol) will count that as ... a lint problem.

Second. We don't know if eslint will find a config file before we run it. So, naturally, we can't disable it before. We can't even cache this information bc then the user had to restart Sublime after running eslint --init. 

We can of course as a hotfix demote/forget this error, but it is not a *good* solution to run eslint in background mode every 300ms to just see it failing silently.

You could disable eslint globally and enable it per project. You could just put a fallback config file in your user home folder. We could exclude files not contained in any project.

**Comment by braver** [comment]
Ok, agreed. Was useful to put a bunch of use cases on the table, but let’s get back to what we can work with and what makes sense. I agree the earlier comments don’t provide good solutions. If we come up with something smart later on we can return to it then. 

I think this is the correct solution:

> You could just put a fallback config file in your user home folder.

This is also ok:

> You could disable eslint globally and enable it per project. 

So, let’s not do anything in SL, users have ways to fix it already.


PS. And IMO it’s pretty stupid that eslint doesn’t come with a built in config like python linters do. Obviously the JS community lacks consensus, or really someone to tell everyone else what the consensus should be. At least jslint had an opinion. 🤷🏼‍♂️
