### ISSUE TITLE
Output panel: double clicking should focus view

### ISSUE THREAD

**Issue by Mitranim** [SublimeLinter/SublimeLinter#1068]
Currently, double clicking a line in the output panel activates the appropriate view and scrolls to the offending spot, but the focus stays in the output panel. Would be much nicer to focus the view so you can edit right away.

**Comment by braver** [comment]
What happens when you interact with the output panel like that is a feature of SublimeText, not of this plugin. We just format and configure the contents of the panel in a certain way and it "just works". So if you want this behaviour to change you need to open an issue in the [ST core issues repo](https://github.com/SublimeTextIssues/Core/issues).

**Comment by Mitranim** [comment]
Oooh that's why I couldn't find this functionality in the SL source. Thanks for explaining.
