### ISSUE TITLE
SL4: please document how to customize colors  

### ISSUE THREAD

**Issue by sebastienbarre** [SublimeLinter/SublimeLinter#1074]
With `error_color` and `warning_color` gone, it's pretty difficult to see errors or warnings because auto-generated color schemes almost never work for colorblind people (and no algorithm will work for all types of colorblindness). These two options were really useful.

I looked at the release notes:

> Each linter setting now accepts such a "styles" setting, so colors, icons and
  highlight style can be differentiated per linter.

But this is too technical for me to understand how to bring back a very specific color (e.g. a RGB hexadecimal value). I tried adding a `color` key inside the style settings that seemed to control errors and warnings, but it was rejected.

Could you please give me a few hints?
Thanks

**Comment by braver** [comment]
I’ll probably document it in more detail later, but this explains what you can do in ST 3143:
https://github.com/SublimeLinter/SublimeLinter/issues/1051#issuecomment-369989146

Dev builds of Sublime Text have more features that will allow you to add your own colors.

**Comment by braver** [comment]
The important part here is to understand how colors work in Sublime Text. Syntax definitions and plugins (like SublimeLinter), label regions of code (and sections of the gutter) with "scopes". You can think of scopes as CSS classes that are set in HTML, saying "this is a variable" and "this is a function". These scopes then receive color from the color scheme, which takes on a similar role as a CSS stylesheet would. So the color scheme says "variables are green" and "functions are blue". 

Now in a perfect world, all color schemes define a color for errors and warnings, saying "errors are red" and "warnings are yellow". Sadly, a lot of color schemes lack colors for such concepts. SL3 approached this problem by copying the color scheme you selected, adding scopes to them, and changing your settings to use that copied and extended color scheme. This was a bad idea for several reasons I won't go into here.

SL4 by expects `markup.changed` or `markup.warning`,  to get an appropriate color for warnings, and `markup.deleted` or `markup.error` something nice for errors. Usually that works, at least for all default color schemes. If it doesn't you need to use a scope that *does* get the color you want from your color scheme. You can inspect what scope each little piece of code gets, so you can use that.

ST dev builds introduced `region.<colorish>` scopes that are generated for each color scheme, so that `region.redish` always gets a color that looks like red and matches the color scheme. This means plugins like SL will get scopes they can rely on.

Additionally, in ST > 3148 there are new features that help users tweak and extend color schemes to their liking.  [This forum post](https://forum.sublimetext.com/t/dev-build-3149/32549) details the new sublime-color-scheme file format and its features. 

For example, if you're using the Monokai color scheme, you can create a `User/Monokai.sublime-color-scheme` file, which will then extend and override the original color scheme. So, you can put this content in it:

```json
{
  "rules": [
        {
            "scope": "my.favourite.red",
            "foreground": "rgb(191,38,4)"
        },
        {
            "scope": "an.awesome.orange",
            "foreground": "rgb(242,183,5)"
        }
    ]
}
```

Now you have 2 scopes you can use, with a nice red for errors and a warm yellow for warnings.

Your SL style setting can use them like so:

```json
"styles": [
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "an.awesome.orange",
            "icon": "dot",
            "types": [ "warning"]
        },
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "my.favourite.red",
            "icon": "dot",
            "types": ["error"]
        }
    ]
```

Now I haven't had enough time with the latest ST dev builds, so this may not be 100% correct or ideal, but this is the basic idea of how it should work. I'll play with it some more and eventually add this info to the real docs.

All of this is perhaps a bit harder to understand than the simple color settings SL3 had. However, it leverages basic functionality in Sublime Text, giving us a lot more flexibility with less effort, and we play nice with other plugins.

**Comment by sebastienbarre** [comment]
Thanks
The new SL4 settings look like this:
```
   "styles": [
        {
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "types": [
                "warning"
            ]
        },
        {
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "types": [
                "error"
            ]
        }
    ],
```
I updated them to look like this:
```
   "styles": [
        {
            "scope": "region.yellowish",
            "types": [
                "warning"
            ]
        },
        {
            "scope": "region.redish",
            "types": [
                "error"
            ]
        }
    ],
```
And neither resulting color look yellow or red (but then again, I'm colorblind, hence the problem).

I've no clue how to extend a color scheme.  How do you specify which color scheme you are inheriting from? Where do they go?

**Comment by braver** [comment]
What version of Sublime Text are you on?

**Comment by sebastienbarre** [comment]
ST3 Build 3143. OK now I see, I missed that you mentioned "dev builds". `region.redish` and others were added in 3148. 

Gotta be honest, it's not ideal to remove two useful options, with no replacement unless you use dev builds...

**Comment by FichteFoll** [comment]
Just a side note, but *very rarely* do things break in dev builds and when they do, the builds either get pulled quickly (in case of terrible regressions) or fixed quickly so that the latest dev build is usually safe to use. It should be noted also that it is still a dev build and breakage *may* occur, so only update when you have time at hand.

**Comment by sebastienbarre** [comment]
Thanks. So far so good. 

> SL3 approached this problem by copying the color scheme you selected, adding scopes to them, and changing your settings to use that copied and extended color scheme. 

Right, and I remember this was such a nightmare, I don't blame you for switching to something better.

**Comment by braver** [comment]
Re-open because I need a reminder to actually move this to the docs

**Comment by jacksbox** [comment]
Just a quick question, as 3149 is a dev build and I want to use a stable one, I have now possibility to add color rules?

**Comment by braver** [comment]
In 3143 you can use all the scopes the color scheme has colors for. To add new ones you would need to copy and then extend the color scheme. I'm going to write an example on how to do that, hopefully today.

**Comment by parejkoj** [comment]
As a user of the older Sunburst color scheme, I have the same question: after upgrading SL, my gutter dots are all white. I'm looking forward to these new docs!

**Comment by braver** [comment]
@parejkoj how much of the part above the horizontal line here is abracadabra to you? https://github.com/SublimeLinter/SublimeLinter/issues/1074#issuecomment-370265068

I'm asking because I'm so used to how all this works, I probably assume too much knowledge in my descriptions.

**Comment by demiurg** [comment]
I wish this was handled in backwards compatible way, it took considerable googling to find this issue.

**Comment by parejkoj** [comment]
> @parejkoj how much of the part above the horizontal line here is abracadabra to you? #1074 (comment)

Er, most of it? I can parse the words, but it doesn't tell me what code I need to write where. For example, SL4 uses `reddish` and `yellowish` for errors and warnings by default. I'd be perfectly happy if I could just put something somewhere that tells SublimeText what those mean for Sunburst and be done with it.

**Comment by demiurg** [comment]
@parejkoj 

Try this in your SublimeLinter settings:

```
    "styles": [
        {
            "mark_style": "stippled_underline",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter comment",
            "icon": "dot",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter invalid",
            "icon": "dot",
            "types": [
                "error"
            ]
        }
    ],
```
I basically just added 'comment' and 'invalid' to defaults, and it works, I have two colors.

**Comment by braver** [comment]
@demiurg If that works depends on the color scheme. Old ones like Sunburst are a bit more tricky.

@parejkoj, if I Iook at a basic javascript file I see a dark orange I could use for errors, and a yellow for warnings:

<img width="408" alt="screen shot 2018-03-08 at 21 00 09" src="https://user-images.githubusercontent.com/2543659/37173400-cb6f9474-2313-11e8-9460-5f60de074e02.png">

If I put the cursor just before the `=` I can then use the Tools > Developer >  Show Scope Name menu item to find out that scope that is:

<img width="587" alt="screen shot 2018-03-08 at 21 01 26" src="https://user-images.githubusercontent.com/2543659/37173466-f4774614-2313-11e8-9816-b072257e6d8f.png">

<img width="299" alt="screen shot 2018-03-08 at 21 02 09" src="https://user-images.githubusercontent.com/2543659/37173479-ff73086e-2313-11e8-9fd4-b6073b5957b9.png">

So, let's hit copy here and put that into the "scope" for errors. Do the same thing for the yellowish color in `getElementById`. This gets me the following styles:

```json
"styles": [
    {
        "mark_style": "stippled_underline",
        "priority": 1,
        "scope": "source.js meta.function-call.method.js support.function.dom.js",
        "icon": "pointer",
        "types": [
            "warning"
        ]
    },
    {
        "mark_style": "stippled_underline",
        "priority": 1,
        "scope": "source.js meta.block.js keyword.operator.assignment.js",
        "icon": "pointer",
        "types": [
            "error"
        ]
    }
]
```

Which looks like this:

<img width="114" alt="screen shot 2018-03-08 at 21 03 37" src="https://user-images.githubusercontent.com/2543659/37173601-540b4cce-2314-11e8-86c7-00856071915c.png">

**Comment by parejkoj** [comment]
Thank you, I'll look at that!

But I'm being somewhat confused by what appears to be different SL4 behavior between different ST windows (e.g. one window is getting my flake8 settings, but the other is not). This seems to also be affecting the color of dots (one window is colored, the other not), so now I'm less sure that the problem is related to my color scheme.

**Comment by kaste** [comment]
@braver that's a pretty good explanation here, even with pictures. Is it possible to copy paste that to the docs?

**Comment by braver** [comment]
Yeah, that’s the intention. Just didn’t make it my highest priority yet.

**Comment by rahilsondhi** [comment]
My errors and warnings were showing up as white too and I was on stable 3143. 

I solved my problem by downloading dev 3154 https://www.sublimetext.com/3
