### ISSUE TITLE
Linters not working

### ISSUE THREAD

**Issue by fily55** [SublimeLinter/SublimeLinter#1089]
When I turned on my Sublime this morning, my user settings were wiped.

If I try to put them back it gives out bout 'user'

> SublimeLinter: ERROR: Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('user' was unexpected)

None of the linters seems to be working. Re-installing the linter also does not seem to put the config into the user setting as it previously did.

**Comment by ronilaukkarinen** [comment]
Just updated and found myself wondering the same thing.

First of all, your old config may be overwritten with defaults since this new update. Old can be found in your User fold with the name "SublimeLinter (old).sublime-settings". I got my old config backed up in [GitHub](https://github.com/ronilaukkarinen/sublime-settings), though had to go it through carefully because many settings were deprecated. I have updated my SublimeLinter.sublime-settings in repo mentioned, if you want to take a look.

As for the phpcs, I found [this](https://github.com/SublimeLinter/SublimeLinter-phpcs/issues/21) to help. For me it helps removing "standard" line altoghether from my user config, that's when it automatically finds project based settings. I hope this helps.

**Comment by braver** [comment]
https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt

> How to upgrade
> -------------------------------
> 
> Your old settings will be backed up to SublimeLinter old.sublime-settings.
> You may want to compare them to the new default settings and check if you want
> to migrate anything.
> 
> To migrate your settings, first remove the "user" level and un-indent/flatten
> everything a level. Check the default settings to remove settings that don't
> exist anymore:
> 
> - mark_style
> - error_color
> - gutter_theme_excludes
> - passive_warnings
> - show_errors_on_save
> - tooltip_fontsize, tooltip_theme, tooltip_theme_excludes, tooltips
> - warning_color
> - wrap_find
> - python_paths
> 
> You can keep the "linters" settings block if it contains customizations that
> you need. It's also safe to remove it otherwise.
> Note that "@disable" is now "disable", without the "@".
> 
> If you use the ${project} settings token you should change that to ${folder}.

**Comment by fily55** [comment]
@braver Ok, that makes sense but it's still not working.

I also had to remove rc_search_limit and use_current_shell_path. It was giving out about these.

The linters still don't seem to get picked up.

**Comment by kaste** [comment]
As always, please enable debug mode and post the console log after a Sublime restart, t.i. from the beginning.

**Comment by kiddick** [comment]
@braver about `@disable` since it is renamed to `disable`, what about `"disable": "C0103, C0111, R0903, R0901, R0913",` for pylint? there is different sense..

**Comment by kaste** [comment]
@kiddick This is completely unrelated to this issue, no? Open an issue or better a PR at pylint. 😄

**Comment by fily55** [comment]
Ah yes, I looked at the errors with debug true and figured out my errors. All sorted now.

I just have a question about the show_errors_on_save. I see there is an error panel that you can show (with a keybind or a command). Is it possible to automatically show this if there are errors when you click save (same as before)?

**Comment by kaste** [comment]
@fily55 Take a look at #1084

**Comment by fily55** [comment]
Perfect, thanks for all the help guys!
