### ISSUE TITLE
Missing Log Messages when plugin fails to lint is confusing

### ISSUE THREAD

**Issue by Narretz** [SublimeLinter/SublimeLinter#1098]
Assume the following:

- SublimeLinter is installed
- debug is `false`
- Plugin A is installed, but the executable cannot be located -> SublimeLinter will warn, e.g. `SublimeLinter: WARNING: plugin deactivated, cannot locate ...`
- I make the executable available
- HOWEVER, during linting, there's a hard error that prevents the linting from working.
- in this case, I will get no log message  *at all* if debug is `false`

This is a very confusing user experience, since SublimeLinter warned about the missing executable before. I propose that when linting fails and debug is *false* there should be a simple message ala "plugin: linting failed. Set debug to `true` to get more information."

(I assume that this behavior is part of SublimeLinter core. Or is this something each plugin should handle itself?)

**Comment by kaste** [comment]
Generally, we use std python logging here. Warnings and errors will always be reported. I did the switch here basically using find-and-replace conquer method. So it's likely to miss something. 

However, it is also possible that lint plugins just eat errors.

So you need to look around a bit maybe. Since these are trivial bugs and fixes PRs are very welcome.

**Comment by braver** [comment]
@kaste can you phrase the state of this issue so that it's actionable for someone?

**Comment by kaste** [comment]
Without info it's not actionable. Hard errors where the `cmd` crashes are logged as `logger.error` throwing in your face. Soft errors where the actual `cmd` succeeds, but the linter shows an error message must be handled by the plugin. Just like eslint does.

**Comment by braver** [comment]
👍🏻
