### ISSUE TITLE
Linter unable to parse settings file after update

### ISSUE THREAD

**Issue by davleh** [SublimeLinter/SublimeLinter#1119]
SublimeLinter: ERROR:

Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('user' was unexpected)

The settings are getting backed up to SublimeLinter (old).sublime-settings on startup, afterwards the linter complains about not finding the settings file anymore.

Is this a bug? Or do I simply have to migrate the settings files? Seems the structure has changed? Is there a documentation about how to to this?

**Comment by davleh** [comment]
I found out how, thanks. :)

**Comment by Shelagh-Lewins** [comment]
Could you explain please how?

**Comment by davleh** [comment]
I followed the instructions given in the console and removed all properties from the settings json that are no longer supported.

**Comment by braver** [comment]
🎉

**Comment by Shelagh-Lewins** [comment]
Ah! The console message actually says that the deprecated setting *has no effect*. This made me assume that it had no effect, i.e. that it was not the cause of the problem.

Following your suggestion I removed the ecmaFeatures section from .eslintrc and now it is working.

I think it would be really, really helpful if the Package Control message and the error message stated that the user needs to change their .eslintrc file for the new version, and that they need to remove the deprecated properties. Otherwise it's not at all obvious.
