### ISSUE TITLE
not work ignore_match and -config for linters

### ISSUE THREAD

**Issue by goodrank** [SublimeLinter/SublimeLinter#1147]
guys how i can actived my ignore warning list? 

```
// SublimeLinter Settings - User
{
	"linters":
	{
		"pylint": {
			"disable": true
		},
		"htmltidy":		{
			"disable": false,
			"args": ["-f tidyErrors.txt -config tidyConfig.txt"],
			"excludes": [""],
			"ignore_match": [
			"missing <!DOCTYPE> declaration",
			"inserting implicit <body>",
			"inserting missing 'title' element",
			"trimming empty <span>"
		]
		}
	}
}
```

and i try add my tidyConfig.txt in arg but nothing =\
    `"args": ["-f tidyErrors.txt -config tidyConfig.txt"],`

**Comment by braver** [comment]
`ignore_match` is gone. 

Did you try writing the args as an array? Is there something of use in the console?

**Comment by goodrank** [comment]
@braver 
i try ``` 	"args": ["-f tidyErrors.txt", "-config tidyConfig.txt"], ``` 
and 
nothing

**Comment by braver** [comment]
Ok, 2 things:

- You don't put the file you want to lint in the args, that's a dynamic thing (you want tidy to lint all your html).
- tidy can't find tidyConfig.txt like this because it doesn't know where to look. `["-config ${file_path}/tidyConfig.txt"]` would be more correct. There are more variables you can use: http://www.sublimelinter.com/en/stable/settings.html#settings-expansion

Now all of this is moot, because the [tidy plugin](https://github.com/SublimeLinter/SublimeLinter-html-tidy/blob/master/linter.py#L28) overrides `cmd` in a way that it (seemingly) won't use the arguments you provide. Now, I'm a bit of my depth here, perhaps @kaste can tell me if what I'm saying is true or bs.

**Comment by mrG0bliN** [comment]
@braver 
if found my tidyConfig.txt in root project folder, cheeeeeer! 💃 
at last need fix ignore-list 
because I collect the pages in parts and I'm straining every time to be distracted by the fact that I do not have a DOCTYPE

**Comment by braver** [comment]
Doesn’t tidy allow you to ignore certain rules in the config file (I don’t know, don’t use tidy much)?

**Comment by mrG0bliN** [comment]
@braver, sorry sir, i did not quite understand what you mean

**Comment by braver** [comment]
It looks like tidy has some configuration options, but not what you need. We won’t bring back a global solution for this, but you could try opening up an issue over at the tidy plugin repo. The plugin could offer some settings to ignore certain rules by parsing the output and removing them from what the plugin reports to SL. 

https://github.com/SublimeLinter/SublimeLinter-html-tidy
