### ISSUE TITLE
New API to pass captured stdout and stderr separately to find_errors

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#1156]
Traditionally, these two streams aren't strictly related in a time-dependant manner. Linters may output lint results on stdout and general usage warnings or errors on stderr. Usually, `find_errors` would only want to operate on stdout while still capturing stderr to look for errors and display those to the user.

There is currently no way to get both of these streams seperately since you can only specify either or have them merged (by simple concatenation).

**Comment by kaste** [comment]
It's not `split_match` but `find_errors`

**Comment by kaste** [comment]
Generally, something like this never gets actionable without an implementation idea (for compatibility). Also probably: Low impact, high effort.

**Comment by FichteFoll** [comment]
I just created the issue for now so it's not forgotten.

**Comment by kaste** [comment]
Okay, this is an important issue for the next release bc right now we see e.g. 'flake8(ok)' in the status bar when actually flake8 crashed. (Try a wrong cli arg. I also have a wonderful broken installation ready to test.)

To move this forward: For STREAM_BOTH linters, we assume stderr holds errors and stdout the normal output. We implement

```
def Linter.on_stderr(self, output):
	logger.warning(output)  
	self.notify_failure()
```

We first report as warning to get feedback from users. Later we switch this to 'logger.error'. 

If we need to opt-out bc there is other useful information in stderr, we set as an 🚨 PR, `on_stderr = None` for the failing plugin. 

Otherwise, we can also override 'on_stderr' to parse the output. 'eslint' will do this bc it prints deprecation warnings on stderr we need to catch.
