### ISSUE TITLE
[docs] expand linter - attributes - defaults

### ISSUE THREAD

**Issue by nvtkaszpir** [SublimeLinter/SublimeLinter#1240]
http://sublimelinter.readthedocs.io/en/stable/linter_attributes.html#defaults

Right now the description of the defaults is without examples - you have to dig through multiple repos of other plugins to get the idea how it works.

Maybe there should be some examples explaining in detail what happens there?

**Comment by braver** [comment]
If you’re creating a new linter plugin, the docs tell you *what* you can use. If you need more details I expect you to read the implementation and its comments, or look for examples in our most popular plugins. 

Some very basic examples would of course help, but the old docs basically repeated the entirety of several plugins. Except of course the docs weren’t maintained and very much out of sync with the reality of those plugins. So, if you keep that in mind I’d welcome some additions to the docs here.

**Comment by kaste** [comment]
You just need to git blame here. We had relatively good documentation for the defaults section and the current documentation is not even correct.

Also: executable is deprecated

**Comment by braver** [comment]
> executable is deprecated

Why not remove it then?

**Comment by kaste** [comment]
I just read this thing, lol

**Comment by braver** [comment]
I'd much rather do this case by case, because not a lot of plugins get made a given week and we might be documenting stuff that's already clear or discoverable. Lots of plugins can be just 5 lines of configuration. And we do have a bunch of examples out there.

Having nice docs is cool though, so definitely appreciated if anyone wants to contribute here.

**Comment by FichteFoll** [comment]
Methods are also severely lacking. I used `context_sensitive_executable_path` earlier today, but that's not mentioned in the docs and I probably wouldn't know about it if I hadn't followed development for months.

**Comment by nvtkaszpir** [comment]
AFAIR SublimeLinter does not have any decent docstrings exported to sphinx.

**Comment by braver** [comment]
> AFAIR SublimeLinter does not have any decent docstrings exported to sphinx.

Nope, we seriously reduced the number of docstrings going into 4.0. Most of them we're outdated and incorrect even before we started working on SL4.

Perhaps waiting for demand for docs is a chicken and egg kind of problem, but as I understand our current maintainers' priorities, documentation is not going to happen all by itself either. Anyone who wants to add some notes, that's super welcome!

**Comment by FichteFoll** [comment]
The behavior of setting a value to `true` or `false` also isn't documented.
In particular, `true` adds the setting verbatim without a value, while `false` doesn't add the setting at all (and als no value, obviously).

**Comment by kaste** [comment]
Closing due to age. The issue does not describe anything anyone would see immediately when looking at the docs so it is not a good reminder. It is thus more like a bad Über-Ich and that usually doesn't help to get anything done.

**Comment by FichteFoll** [comment]
I don't know about anyone else, but I don't even look at the docs anymore nowadays. I've been disappointed by them beeing outdated or not containing the necessary information one too many times that I now go into the source code pretty much immediately and read the docstrings, function signatures and sometimes bodies there.

Of course that doesn't help you in identifying which areas in particular need to be updated, because I don't even remember myself, but there are definitely issues with the current state of the docs.

**Comment by kaste** [comment]
The docs are in part terrible, it's just that this issue (apparently) did not motivate anyone to make them better.  (Actually an online/offline editor, WYSIWYG, would help me a lot.)

**Comment by braver** [comment]
You think the public docs are bad, you should've seen the docs in the code before SL4. There's lies, damned lies, and documentation. 

For me the important part is that we make the core package excellent. That's where the work should go and that's where the work pays off. Hardly anyone ever writes a plugin because the important ones already exist. And 99% of the plugins don't need any maintenance, so no one needs to read documentation to do the maintence. In fact, it's the maintainers of the core package that do most of the maintenance on plugins as well, and that is again a lot more efficient than writing documentation and hoping for the community to pick up the ball. 

There are lot's of plugins out there. That is also a kind of documentation. 

I'm more if favor of removing documentation than updating it or writing more. That said, I wouldn't mind so much if it was in markdown so a normal person can read and edit them. So I would actually like to take down the documentation site, migrate the docs to markdown, and let someone who wants to read it just read it here on GitHub.

**Comment by kaste** [comment]
Just checked `rst` files are now editable and formatted in GitHub.  👀 This will make it easier.
