### ISSUE TITLE
panel reopens again after I close it (using show_panel_on_save)

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1303]
Perhaps caused by reports continuing to roll in after I hit save:

- set `show_panel_on_save` to "window"
- have a file with some errors, preferably with multiple linters (e.g. html with embedded css and js)
- hit save
- the panel opens immediately 
- quickly hit ESC
- the panel closes, then opens again

**Comment by kaste** [comment]
This is exactly as designed. So the 'bug' repro is not the problem here. Not sure what the user story here is. 

The panel shows up imm if some linters are in background mode and dirty. So the error A might show. The user imm hits ESC closing the panel. Now new results fly in, 

- with error A and B => panel should probably open again?
- only with error A => panel should not open?

**Comment by braver** [comment]
Yeah, good point. Wouldn't it be nice if everything in the world was synchronous? Like the "close the panel" command would be queued and only executed after all linters we're done with their work, and then canceled if there are errors. It would be super slow but also perhaps calming and zen. "Just relax and wait for your computer". 

But. Idea:

Perhaps, it would be best if I hit save **once**, then the panel will also only be opened **once** because of that trigger.

**Comment by braver** [comment]
Hm,  no, actually the current behavior is probably correct. If someone else feels really strongly one way or another we can always revisit.
