### ISSUE TITLE
Automatically FIX file on save

### ISSUE THREAD

**Issue by kirylpl** [SublimeLinter/SublimeLinter#1305]
Is there any way to use subject option if linter provides the mechanism for that ?

**Comment by braver** [comment]
This issue covers the subject: https://github.com/SublimeLinter/SublimeLinter/issues/375

In many cases SublimeLinter passes files to the linter using stdin, or temporary files. Fixing definitely won't work in that case. If the linter plugin is set up to run on the actual files on disk only it might be possible just by passing the `--fix` argument. For TypeScript for instance it probably works but I haven't tried. 

You opened the same question for stylelint and there it definitely won't work because we use stdin. How a file is sent to a linter plugin isn't configurable right now.

A bunch of work would need to be done to enable fixers. I'm not saying we wouldn't want to do that, but right now it's not really a good fit and not a very high priority.

**Comment by kaste** [comment]
Closing bc this is not actionable. Hackers can prototype in a fork, but we don't need an issue for that. 

That being said, I use prettier and yapf plugins and they work good with SL. So I actually don't know why we need a all-in-one solution here.

**Comment by braver** [comment]
Well, we usually run tslint and eslint with a `—fix` arg, which means you don’t have to tell me about the errors it can fix. So it makes sense to be aware of that. But the idea has been sitting here for years, it’s just not going to happen.

**Comment by kaste** [comment]
Hm, we could tell eslint plugin to filter fixable errors.  For sure you don't want fix while editing. I doubt you can even run it on save bc it probably removes debugger statements or whatever.

Now, you can just fork the eslint plugin to eslint-fix. Adjust cmd to operate on $file instead of stdin, set lint_mode to manual or save. Then just ignore the output, you still have the other eslint plugin for that. And see how this works.

**Comment by braver** [comment]
Oh, I actually don't mind seeing the errors even if the linter will auto-fix it later. I usually want to internalise the rules and type correctly right away. I also still think caring about auto-fixers in SublimeLinter is a bad match, and that there are already enough features here (e.g. styles etc) to filter if you want. And I'm not stopping anyone from running a file watcher + fixer on the side either. So, I'm good.

**Comment by kaste** [comment]
Ok, PR for eslint is https://github.com/SublimeLinter/SublimeLinter-eslint/pull/254
