### ISSUE TITLE
Underline Style and slow TSlint

### ISSUE THREAD

**Issue by it6** [SublimeLinter/SublimeLinter#1360]
When I changing my setting to one of these `"solid_underline", "squiggly_underline", "stippled_underline"` they all fall back to outline style.

```
// SublimeLinter Settings - User
{
  "styles": [
    {
      "mark_style": "solid_underline",
      "priority": 1,
      "scope":
        "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
      "icon": "dot",
      "types": ["warning"]
    },
    {
      "mark_style": "solid_underline",
      "priority": 1,
      "scope":
        "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
      "icon": "dot",
      "types": ["error"]
    }
  ],
  "statusbar.counters_template": ""
}
```

TSLint is so slow. After a change is made I have to wait for 5-10 seconds to see the error showup, this is not the case with the previous version.

**Comment by braver** [comment]
One is because we fall back to outlines if there is white space in the error regions. Search the issues if you want to know more.

The slowness of tslint shouldn’t be something we caused, but I noticed it being really slow lately too. Perhaps just an update on their end. Or it’s doing project-based linting with type checking now, which probably involves compiling a lot more than the current file. Please open an issue in the SL-tslint repo if you want to investigate further.
