### ISSUE TITLE
Error in sublime-settings configuration upon recent upgrade

### ISSUE THREAD

**Issue by aphearin** [SublimeLinter/SublimeLinter#1433]
I have been using SublimeLinter v4 for a few months and recently updated st3. After rebooting st3 after the upgrade, I am now getting the following error:

```
SublimeLinter: ERROR:

Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
'' is not of type 'boolean'
```
It seems this could be related to #1070, so cc @braver.

I am running on OS X 10.12.6 with  st version 3.1.1, build 3176, and with SublimeLinter version v4.6.2. 

Simply uninstalling and re-installing SubmlimeLinter via Package Control does not resolve the issue.

**Comment by Cerberus-tm** [comment]
I got this error too. I solved it by removing lines from my user settings that set a value to "" (an empty string). I think I removed all the settings for gslint, flake8, and pydoc.

**Comment by braver** [comment]
We’re guarding the implementation against invalid settings by validating them. We made that more strict recently. It also helps you keep your settings sane so you don’t have to debug weird behavior somewhere down the road. The default settings should provide enough guidance to help you set them correctly. If you don’t, you get feedback what you’re seeing is not an error/bug report, it’s feedack to you that you made an incorrect setting).

Tips:

- if you want to return something to the default setting, comment that line instead of giving it an invalid value 
- the opposite of true is false, not “” or some other falsy value
