### ISSUE TITLE
Local binary support

### ISSUE THREAD

**Issue by andrewdeandrade** [SublimeLinter/SublimeLinter#144]
I'm looking into adding support to the linters based on binaries installed with npm, so that they can use the local binaries installed in the `node_modules/.bin/` folder of the current project. 

For example, the https://github.com/SublimeLinter/SublimeLinter-jshint linter currently requires jshint to be installed globally with `npm install -g jshint`. Instead of having it look for that global binary in the path, I want to override the `cmd` or `executable` properties of the linter class to find the local binary. I want to add this type of support to linters for jshint, jscs, csslint, eslint, etc.

With this in mind (and the fact that I'm relatively new to python), can someone give me a few hints on what APIs (assuming SublimeLinter already has the APIs to support this use case) I need to use to get access to the current path of the file being edited, so I can use it to probe upwards until I find a `package.json` file, then probe the `node_modules/.bin` folder for the binary before falling back to the global `$PATH`.

**Comment by mderazon** [comment]
This creates a problem with pluggable linters such as eslint.

Eslint has a plugin system, you can define to use a plugin like `eslint-babel` in the `.eslintrc` and eslint will use it. You would have to install the `eslint-babel` separately from eslint. The following scenario creates a problem:

1. You use `eslint` and `eslint-babel` globally. 
2. Your package.json has some dependency that depend on eslint and thus eslint is being poured into the project `node_modules/.bin` folder but `eslint-babel` doesn't end up there
3. Linter looks for local binary first and finds eslint in the bin folder and uses it
4. Linter throws exception since it can't find `eslint-babel` as it's not in the local folder but rather in the global folder.

I had this exact scenario happen to me and described here https://github.com/roadhump/SublimeLinter-eslint/issues/31#issuecomment-119725202
