### ISSUE TITLE
Unable to open SublimeLinter.sublime-settings

### ISSUE THREAD

**Issue by YoavGivati** [SublimeLinter/SublimeLinter#1452]
SublimeLinter suddenly stopped working after the last update. 

If you open up the console ```ctrl + ` ``` it says `Unable to open ~/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/SublimeLinter.sublime-settings`. 

It’s because that folder no longer exists. reinstalling doesn’t fix it. 

My workaround to get it working again was to: 
1) manually create that folder/file
2) use `cmd+shift+p` and  open sublimeLinter settings
3) copy the default settings from the left side into the file you just created.

**Comment by kaste** [comment]
Hm, for installed packages `Sublime Text 3/Packages/SublimeLinter/` generally will not exist bc the package is installed in `Sublime Text 3/Installed Packages/`. 

What you now have @YoavGivati, is a package override. You have a file with the same name extracted, we usually ship. And your file will take precedence from now on. 

If you could open the default settings for copy/paste, then SublimeText could actually extract/find them.

I would recommend to delete the files you recreated, bc otherwise you will not see updates for these files.

**Comment by md-mkane** [comment]
I get this problem too, since Friday.  Here's a full console dump:

startup, version: 3176 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/markkane/Library/Application Support/Sublime Text 3/Packages
state path: /Users/markkane/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/markkane/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.386597
using gpu buffer for window
using gpu buffer for window
startup time: 0.5656
environment variables loaded using: /bin/bash -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Git.git_commands
reloading plugin Indent XML.indentxml
reloading plugin Indent XML.setup
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SelectUntil.edit
reloading plugin SelectUntil.select-until
reloading plugin SublimeLinter-pylint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Sublimerge 3.Sublimerge
reloading plugin Theme - Monokai Pro.Monokai Pro
reloading plugin SFTP.SFTP
plugins loaded
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:49: debug mode: on
SublimeLinter: sublime_linter.py:50: version: 4.6.4
SublimeLinter: sublime_linter.py:238: Delay buffer 57 for 0.0s
Package Control: Skipping automatic upgrade, last run at 2018-06-18 08:29:14, next run at 2018-06-18 09:29:14 or after
SublimeLinter: sublime_linter.py:238: Delay buffer 30 for 0.0s
SublimeLinter: sublime_linter.py:238: Delay buffer 89 for 0.0s
using gpu buffer for window
Unable to open /Users/markkane/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/SublimeLinter.sublime-settings
SublimeLinter: sublime_linter.py:238: Delay buffer 134 for 0.0s

**Comment by braver** [comment]
I can't replicate this at all. We don't access the settings via the path directly but only via the ST api.

**Comment by alb3rto269** [comment]
same problem here.

**Comment by kaste** [comment]
What's the impact here? Is SublimeLinter essentially dead after that? Does it go away after restarts?

**Comment by braver** [comment]
Discussed this with some other package devs. Their experience mirrors mine here. 

To be clear, we're not accessing the settings in any way that would throw this error. This isn't an error caused by something that Sublime Text by itself, or SublimeLinter, is doing.

> What's the impact here?

There probably isn't any. This type of message is thrown when the default and packaged settings file is accessed directly, which isn't possible, after which Sublime Text opens a read only view for the settings file anyway. There is something else in the setup that's causing this that we can't see from the logs.

**Comment by mikermcneil** [comment]
> What's the impact here?

In our team's case, it means that your settings aren't read, which means they don't apply (which in our case, means the configuration specifying the path to `node` doesn't apply, and the package stops working)

**Comment by kaste** [comment]
@mikermcneil 	Can you replicate that, or is it once-in-a-while? Installed via Package Control or `git clone`? Do you have the settings actually open for editing in a different window?

**Comment by ehausen** [comment]
I also have recently got this issue
`Unable to open /Users/MyName/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/SublimeLinter.sublime-settings`

The impact is that my custom settings are not read and the default is used.
I tried removing sublimeLinter package with package manager and then reinstalling it with package manager, did not try removing files or folders manually.

**Comment by kaste** [comment]
@ehausen That's still odd and hard to understand. It says it can't open the *default* settings, and then you say it uses the default settings but actually ignores the user (custom) settings.

Generally, afaik, the message is thrown like so:

```
>>> window.run_command('open_file', {'file': 'my/foo/bar'})
Unable to open /C/Users/kaste/Desktop/Default/my/foo/bar
```

(You could try this in the Sublime console.) Here, I run the standard open command for a non-existent file. This matches your error message. Sublime will then instead open a new empty file ready to work with and with a future file name already set.

It can of course be that the same error message is thrown under different circumstances, but I don't know nothing about it. 

SublimeLinter will *NOT* invoke this command. But the settings view will, so the idea was that you have a window open with edit settings in the background. Now to replicate the error message:

- Open the split screen settings for an installed package.
- Do not close the window, but restart Sublime
- After restart, the default settings tab will be gone. You still have the split screen, but the left 'pane'(?) is empty, the right shows the user settings. (BUG1!)
- Open console to see the error message popping up next.
- Okay, open the same settings again. Using the `Preferences > ...` menu.
- A new window will popup, showing everything as expected, *but* the error message will be logged. (BUG2!)

(This only replicates the error message nothing else!)

**Comment by ehausen** [comment]
I think I fixed this by uninstalling, removing config files and reinstalling.

**Comment by TejasAvinashShetty** [comment]
I am facing the same issue. So, I tried opening  the said file via Preferences > Package Settings > SublimeLinter>Settings. It says 
>Unable to open /home/shetty/.config/sublime-text-3/Packages/SublimeLinter/SublimeLinter.sublime-setting
 
But I am able to view the user settings file. I have verified it (It has all the changes I have made)
