### ISSUE TITLE
per folder linter settings

### ISSUE THREAD

**Issue by mathroc** [SublimeLinter/SublimeLinter#1474]
I know I can set per project linter settings. In a single "project" (eg: with a lot of repositories managed by different teams) sometimes I'd like to set different settings per folder (eg: use a different config file)

It could work by creating a project in sublime for each repositories but it would be quite cumbersome because it would mean we'd have to open a lot of sublime window to work across the many repositories

would that be in the scope of SublimeLinter?
thank you

**Comment by braver** [comment]
Linters like eslint that have config files, will search "up" from the current file to look for their project's root and configuration. In most cases using the linter's native configuration enables this behaviour without you having to specify anything in SublimeLinter. 

We lean on Sublime Text's API's for merging different levels of configuration, ensuring that it just works everywhere and works just like all other packages in the eco system. 

SublimeLinter tries to be a lean wrapper around linters to make them work from within Sublime Text and then provide a unified UI. If the linter doesn't offer anything smart to find its configuration, and Sublime Text doesn't offer a way configure something, we probably don't want to step in and provide a solution. It's going to be both a corner case *and* a huge amount of work because there is no plumbing for us to lean on, plus we will have to find a way for it to work with ST's config merging system without breaking it.

**Comment by kaste** [comment]
We currently don't have a super strong vision for big repos/monorepos etc. Instead of a proposed solution (folder settings) we first need a better understanding of the problem. 

What we have today: In Sublime projects, you can open/reference multiple folders. The SL context variable `$folder` will point/expand to the first matching folder for a particular file. E.g. in a project file

```
  "folders": [
    {"path": "./bar"},
    {"path": "./foo"},
    {"path": "."},
  ],
  "settings": {
    "SublimeLinter.linters.somelinter.args": ["--config", "$folder/.somelinterrc"],
    "SublimeLinter.linters.somelinter.working_dir": "$folder"
  }
```

Now, SublimeLinter will set the working_dir to "./bar" if you edit "./bar/myfile.js", and use "./foo" for e.g. "./foo/otherfile.js". Likewise, it will use different config files.

FWIW as always.

**Comment by mathroc** [comment]
@kaste thankx that's good to know, might be enough in some situation (but doesn't help in mine because the relative path is not always the same)

fwiw, a solution with settings per folder would be fix my problem

not sure if that could be integrated more easily in SublimeLinter though, if not, feel free to close this issue

**Comment by braver** [comment]
I think ideally the SL config is about your preferences and should be applied globally. E.g. you like to ignore some warnings. Linters should have their own configurations, you should be able to pread that over the file system and let the linter figure out what config to read.
As it is though, this model doesn’t work for many projects. Usually because the linter comes up short, e.g. it doesn’t provide a way to set certain config with config file and we have to construct args. So SL steps in to help you be productive anyway. Or because we don’t always work on modern and up-to-date code bases.

This idea of the monorepo also isn’t something the open source community, particularly for JS and Python, which is where most of these linters come from, is used to. I think Eslint and Tslint work well in that environment, perhaps because they have serious companies contributing to them, perhaps because they have more users than the other linters combined. For most tooling though, monorepos aren’t even considered.

A monorepo with a weak linter, in Sublime Text, is basically a worst case scenario. I’m not sure SL can fix it if the entire structure doesn’t understand monorepos. It’s also not just a linter issue, it applies to build systems etc. as well.

**Comment by kaste** [comment]
So, this is relatively cheap to implement within the current system. 

The only problem is, that we cannot search everywhere for such a '.sublimelinterrc' file, so the constraint would be that we only search for such files in the folders listed in the project file.

Of course, some upvotes, more user stories would help bring the issue forward.

**Comment by kaste** [comment]
Iirc Vscode relatively similar has multiple folders per window and uses the project settings of the folders if they have any. And merges them with the workspace settings.

That's reasonable probably.

**Comment by braver** [comment]
Sure, but project settings in VS Code are completely different from project settings in SublimeText. In VS Code they are inherently tied to a directory, they sit in a `.vscode` (IIRC) directory in the root of that directory. A ST project can have any number of "root directories", but only one settings object. If we're going to look for settings per root directory, we might as well add directory-specific settings as a general thing. Which may be actually a more elegant approach than littering `.sublimelinterrc` all over the file system and having them end up in codebases.

However, remember that a file can belong to multiple directory trees, i.e. child directories and duplicate directories can sit in the same project. Once the file is open you don't know which tree the file belongs to, so you don't know which one to read the settings from (or you need a way to resolve that).

So what I would propose to consider is adding a "directories" array to the SL settings and allowing the "linters" settings to be replicated there. When linting a file, check if it's inside one of those directories, take the settings from the longest directory path that matches. Use those settings for a linter instead of those already merged (or perhaps look into merging). This will allow you to change settings for specific directories without having to set up and use ST projects, or dropping hidden config files somewhere, but you *can* still do the same thing per project and get fine granularity.

**Comment by kaste** [comment]
You mean to put it into the "global" SL settings. That looks ugly (deep nesting) and is cumbersome to edit. It usually doesn't scale bc you're always hesitant to delete an entry. 

What I thought, just to clarify. You open the project using a ".sublime-project" file. Within that file you have multiple folders open. We already have a simple algo to determine which file belongs to which folder (if at all). Then we look at that folder if it contains a ".sublime-project" file. If yes, we merge the settings object with the one from the original (actual open) project.

**Comment by braver** [comment]
Ah, but sublime-project don’t necessarily live inside, or even near, the project. They can also be moved. They are completely unlike vscode projects. It just doesn’t make sense to look for those files in parent directories, that pattern doesn’t apply here.

**Comment by kaste** [comment]
Everything can be moved, but you can also make your life easy and put these files in your working dirs just like Code. You already have 'node_modules', 'mypy_cache's, '.git' folder here.

> Also consider projects with multiple directories.

I talk about projects with multiple folders open.  😕

**Comment by braver** [comment]
Yeah you do, but if I have multiple folders in my project, which contains the sublime-project file?

In my sidebar:
/patha/dir1
/pathb/dir2

There is only one sublime-project file that describes this setup, so where do I put it? It doesn’t make sense to have project files in both directories, because only one of the two will be the project that’s loaded by ST.

So, that’s the fundamental misunderstanding here. Sublime projects are nothing like node_modules, .git, .vscode, because they are in no way tied to a single directory.

**Comment by kaste** [comment]
Yeah, okay. The actual "active" or "open" ".sublime-project" can live wherever you want bc we have an API to get that and its contents. 

So, you open a project pointing to two folders. This project can already have some SL settings which basically get applied to all files within that project. But now we want to support even finer-grained settings.

- We could look generally for a '.slrc' file but 👎 we don't want to traverse all the directories all the time, and we don't want such a file type at all anyway.
- We store information in a central place like the global SL settings but 👎 it leads to an ever growing settings file, and basically the global settings now contain local settings.

So, if you load this project we already have access to the two folders via the API. Instead of traversing the dirs we just look at '/patha/dir1/*.sublime-project' or '/pathb/dir2/*.sublime-project' depending on the active view, and if there is such a file we read it and merge its settings. 

To require a '/patha/dir1/*.sublime-project' is not totally stupid bc if these sub-projects are reasonable decoupled you may want to work with them separately at some time and maybe already have such a file. But the requirement is ours bc we don't want to look at arbitrary locations (search) for it. We could also look for 'patha/dir1/.slrc', we still wouldn't traverse but we would add a new file type for no good reason.

(Generally, if you have a bigger code base with decoupled sub-systems, you want to work on them in a per window style with multiple projects or workspaces as often as possible. goto-anything, or goto-symbol, are way better. Also switching projects/workspaces is nearly instant and a prime feature of Sublime.)

**Comment by braver** [comment]
I agree with your approach, except that the settings should not live in a .sublime-project file. Those files have a purpose, and usage, and it's not a good idea to repurpose them as you suggest now. Instead, we could look for a .slrc file in the root directory. No need to traverse directories, just look in the root directory and if it's not there it's not there. And it can be just our settings object in a json file. If we're going to have custom handling for it anyway, we don't need the config to exist in the sublime-project file.

**Comment by kaste** [comment]
I totally follow here. But then it's not a simple addition anymore. We need to deprecate the config in the '.sublime-project' files. We currently follow the Sublime standard by just looking for view settings (minus deprecated code) which comes for free bc these settings are always in memory, no caching, no traversing, no file reading. (Confusion reminder: Sublime merges the project settings into the so-called view settings.) 

So, we had to deprecate the standard project settings, add our proprietary '.slrc' file. We still *technically* had to merge in the view settings but now only for the fine grained per-view modifications. On the 👍 we had the simpler deep object json contents in such a 'rc' file you could easy-copy-paste from the global settings, in contrast to the flat key-value pairs you have to type in the project file.

You have to beat me to the 'slrc' file thingy. 

With my only 'sublime-project' files approach it would have zero impact for the 99% use-case where you only have one folder in a project. Also at least notice that it is totally reasonable that the subprojects of big projects also need their own project/workspace files. 'subl .' is nice but it is - just with how Sublime manages the view settings - a core, prime feature to switch between projects/workspaces instantly. I don't want to repurpose the project files, I assume there are already there, not 100% all the time but often. (Needless to say: yes we have options, sometimes the multi-group/pane stuff is okay, but *I* usually work with multiple windows, I can arrange them side-by-side on any OS, symbols and goto anything work 👌, the panels are always per window and thus have a sane width automatically.)

**Comment by braver** [comment]
I’m not sure, but it seems like you think that Sublime will read the sunlime-project files in each root directory. It will not, it only reads the file you opened directly. Any other project files are just json files for as much as Sublime  cares. To read what it’s in them and merge the settings, we need to create a custom solution. Also, if you open a directory with a sublime-project file in it, Sublime does not read that file. If we *are* going to read that file, we are effectively repurposing them because we’re using those files in a way Sublime never intended.

Or am I missing something here and you know something about Sublime projects that I don’t?

**Comment by kaste** [comment]
I don't have any tricks here. 

The current story is we have local config in project files. These already don't apply if you just do a 'subl .', so a user must have a workflow to handle Sublime projects. From that, for bigger repos, we currently advocate for multiple project files, and with it a multi workspace/window solution. We follow Sublime here in that project switching is instant, and generally window management by our OSes is great these days. 

With that, basically just the Sublime standards, we easily got our 80% if not more solution. 

Compared to that '.slrc' is the fully custom, self-made version. Would we like to see a '.gitsavvyrc' as well? And so on. Should we support 'subl .'?

I'm not for new file types, and I don't want to deprecate Sublime project settings. 

Two other options: 1. Since everything is standard, it is possible that users write a small plugin which applies settings dynamically. 2. Just write a short shell wrapper for your linter which applies different args dynamically.

**Comment by braver** [comment]
Oh I don’t really want our own config files. I ripped them out because I think they shouldn’t exist and I think the use cases it covers are few and dwindling. Also, as you say, current day window management is excellent. I like discussing possible solutions though.

I think your #1 is good also. It’s not necessarily up to us to come with a solution here. Also consider that we haven’t supported this for a year now and it hasn’t affected our stock market value 😄

**Comment by braver** [comment]
This discussion has no actionable outcome. Everyone once in a while the subject comes back and it’s never bad to re-assess if we need a feature. However, I don’t believe there is enough demand, especially when compared against the effort and impact of any of the considered approaches. At least at the current moment. So, I’m archiving this, we can always point to this or the related discussions if/when the topic returns.
