### ISSUE TITLE
SublimeLinter not respecting custom config

### ISSUE THREAD

**Issue by jonathansimmons** [SublimeLinter/SublimeLinter#1511]
So I feel like I'm going crazy, we have a repo of all our linter configs that we share across our devs. The benefit is that when someone updates, we can just `git pull`. So the idea is that our respective IDE would just be pointed to the repo folder where the respective linter configs live. However in my testing it appears that SublimeLinter is just outright ignoring the arguments we told it to run with. 

example config 1:
```json
{
  "debug": true,
  "delay": 0,
  "gutter_theme": "",
  "lint_mode": "background",
  "linters": {
    "scss": {
      "@disable": false,
      "args": [
        "--config=/absolute/path/to/.scss-lint.yml"
      ],
      "exclude-linter": "",
      "excludes": [],
      "include-linter": ""
    }
  },
  "no_column_highlights_line": false,
  "paths": {
    "linux": [],
    "osx": [
      "~/.rbenv/shims"
    ],
    "windows": []
  },
  "show_marks_in_minimap": true,
  "syntax_map": {
    "html (django)": "html",
    "html (rails)": "html",
    "html 5": "html",
    "javascript (babel)": "javascript",
    "magicpython": "python",
    "php": "html",
    "python django": "python",
    "pythonimproved": "python"
  }
}

```

example config 2: 
```json
{
  "debug": true,
  "delay": 0,
  "gutter_theme": "",
  "lint_mode": "background",
  "linters": {
    "scss": {
      "@disable": false,
      "args": [
        "--config",
        "/absolute/path/to/.scss-lint.yml"
      ],
      "exclude-linter": "",
      "excludes": [],
      "include-linter": ""
    }
  },
  "no_column_highlights_line": false,
  "paths": {
    "linux": [],
    "osx": [
      "~/.rbenv/shims"
    ],
    "windows": []
  },
  "show_marks_in_minimap": true,
  "syntax_map": {
    "html (django)": "html",
    "html (rails)": "html",
    "html 5": "html",
    "javascript (babel)": "javascript",
    "magicpython": "python",
    "php": "html",
    "python django": "python",
    "pythonimproved": "python"
  }
}

```

When I look at the debug log I see the command: 

```bash
$ cat app/assets/stylesheets/application.css.scss | /Users/jonathansimmons/.rbenv/shims/ruby -S scss-lint absolute/path/to/app/assets/stylesheets/application.css.scss
```

which seems to be devoid of the custom config arguments. 

Further, I tried to simply toggle the `@disable` option to true and the linter still ran. It's as if SublimeLinter is ignoring my settings altogether.

Any help or direction would be appreciated. As of right now, the only fix is to copy the linter config to the root directory of the repo. This works but it eliminates the advantage of the specified location mention above.

**Comment by braver** [comment]
Looks like you missed how SublimeLinter 4 changes settings. Let's at least cut it down to something more practical:

- remove all settings you didn't change from the default, ie. `show_marks_in_minimap`, `syntax_map`,  `no_column_highlights_line`: they do nothing and can only turn around to bite you later.
- `@disable` isn't a setting anymore, it's just [disable](http://www.sublimelinter.com/en/stable/linter_settings.html#disable) now without the `@`

It looks like you're using the [Sublime​Linter-contrib-scss-lint](https://packagecontrol.io/packages/SublimeLinter-contrib-scss-lint) plugin, which according to [its documentation](https://github.com/attenzione/SublimeLinter-scss-lint#settings) should be configured via the `"scsslint"` key instead of `"scss"`.

You should also remove the `"exclude-linter"`, `"excludes"`, `"include-linter"`. Only `"excludes"` is actually a settings that still exists, the others are probably from some previous version and don't do anything. If you're not going to set them, don't keep them around because they'll just get outdated and confuse people.

**Comment by jonathansimmons** [comment]
@braver Thank you so much. A long day of staring too closely at my screen. I had copied the config from another dev that set up a readme for department linters. The key was wrong there but I should have noticed that. 

Thank you so much.

**Comment by braver** [comment]
Nice! 🎉
