### ISSUE TITLE
Panel location / sidebar, tab, window?

### ISSUE THREAD

**Issue by ronilaukkarinen** [SublimeLinter/SublimeLinter#1517]
I was just wondering is it possible to show panel anywhere elase than on bottom? It's good "enough" in bottom of course, but it would be even more awesome to see the results in separate window, split window or even sidebar. Possible?

Current view:
![Screenshot](https://i.imgur.com/mXjMb4c.png)

**Comment by braver** [comment]
Sublime Text only has a "panel" on the bottom. You can create other views that will appear as a tab, but they won't have the same features as the panel because it would lack that specific API. You'd lose some of the interactions like being able to jump to prev/next results in the panel. It should be relatively easy to re-create something like the Find Results view though, without specific panel-only features but as something you can open on the side as a reference or overview. We currently don't have plans for features like that, so that would have to come from someone contributing a PR.

**Comment by ronilaukkarinen** [comment]
OK, thanks for the information. I'm not that experienced in improving ST itself so have to leave this as a sitting issue to wait if someone has hopes and means to contribute.

**Comment by ronilaukkarinen** [comment]
I managed to achieve what I was looking for by installing [gulp-scss-lint](https://github.com/juanfran/gulp-scss-lint) and [gulp-phpcs](https://github.com/JustBlackBird/gulp-phpcs). That way I can keep Sublime panel mostly hidden and, look to another monitor for errors in gulp, then open the panel and fix them directly. So best from both worlds: I can have linters in separate window and fix them with SublimeLinter. 👍 

So practically it's reinventing the bicycle if you implement this to SublimeLinter/Sublime Text, so as far as it comes to me, this issue can be closed.

**Comment by braver** [comment]
Ok 👍 If we ever want to do something like this it'll come up by itself again.
