### ISSUE TITLE
Using a carrot in an argument causes plugin_host to crash.

### ISSUE THREAD

**Issue by envygeeks** [SublimeLinter/SublimeLinter#1527]
```
/Users/jordon/Development/f1  (working dir)
$ /Users/jordon/.bin/subl-golint --include='^twitter.go' --vendor --disable-all --aggregate --tests --enable=gosec --enable=golint --enable=vetshadow --enable=ineffassign --enable=goconst --enable=gocyclo --enable=deadcode --enable=safesql --enable=vet .
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

However, when we don't do `--include='^twitter.go' in our linter, it doesn't crash.

**Comment by envygeeks** [comment]
It also seems to crash with '\A'

**Comment by kaste** [comment]
Generally, plugin_host crashes are out of scope. That's Sublime's sandbox and it should never crash. (There is a bug on the current 'stable' (LOL) where this happens if the program your calling crashes. This has been resolved on the latest dev builds afaik.)

Anyway. Looks like you're doing the quoting here, and this probably causes the crash.

**Comment by envygeeks** [comment]
Indeed you are right, I should have closed this as I solved it an hour after I posted the ticket by checking the dev builds and updating, and then all the problems I've been having were magically solved.  Sorry about not closing this.
