### ISSUE TITLE
Remove deprecated features (first candidates)

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1583]
- Remove the old 'cls.syntax' handling.
- Remove special '@python' handling in `cmd`
- ~~If possible remove deprecations in `finalize_cmd` bc we have plugins hacking around here to prevent auto appending.~~
- ~~Log as error in `on_stderr`~~

**Comment by braver** [comment]
Wanna do this as a 4.x, or move to 5?

**Comment by kaste** [comment]
4.x

I think bigger plugins like SL or GitSavvy are apps, and so a v5 must have big UI/UX impact. Technically, we shipped a lot of gradual breaking changes. The latest 4.10 is technically a 5.0. Other than that, I don't care, the semantic versioning here is fake bc users have the latest version installed automatically anyway. 

As a last step before removing, we could also show an error message in-ya-face. All three things above are trivial to update in the plugins, like 5 minutes work.

**Comment by braver** [comment]
Oh, totally agree, just to consider if we're breaking an API. But we can break API's no-one uses because we have access to all users of the API. And those we can't write to probably won't update until we really break them because maintainers are lazy (I should know ;)).

So, I'm all for this, just push ahead and drop the old stuff. 👍

**Comment by kaste** [comment]
Also: in `on_stderr` log as error, we announced this change long ago.

**Comment by kaste** [comment]
We actually only shipped two of the bullets in 4.12.0 🤷‍♀
