### ISSUE TITLE
SublimeLinter-golangcilint: no output

### ISSUE THREAD

**Issue by kortschak** [SublimeLinter/SublimeLinter#1586]
I have just installed SublimeLinter (v4.10.0) and SublimeLinter-golangclilint (v1.1.1) via package control. golangci-lint is installed at v1.15.0.

I am unable to obtain any linting information via the SublimeLinter interface in ST3 although I can get this information from golangci-lint.

For example linting this file with an unreachable path (the addition shown in the gutter at line 89) results in `golangclilint: no output`

![linter](https://user-images.githubusercontent.com/275221/55285967-f895fb00-53dc-11e9-8653-a390c9c62d5a.png)

Running essentially the same command invocation on the command line gives me the expected result:
```
$golangci-lint run --fast --out-format json
{"Issues":[{"FromLinter":"govet","Text":"unreachable code","Pos":{"Filename":"barneshut3.go","Offset":1508,"Line":89,"Column":4},"SourceLines":["\t\t\treturn ne"],"Replacement":null}],"Report":{"Linters":[{"Name":"govet","Enabled":true,"EnabledByDefault":true},{"Name":"errcheck","Enabled":true,"EnabledByDefault":true},{"Name":"golint"},{"Name":"staticcheck","EnabledByDefault":true},{"Name":"unused","EnabledByDefault":true},{"Name":"gosimple","EnabledByDefault":true},{"Name":"stylecheck"},{"Name":"gosec"},{"Name":"structcheck","Enabled":true,"EnabledByDefault":true},{"Name":"varcheck","Enabled":true,"EnabledByDefault":true},{"Name":"interfacer"},{"Name":"unconvert"},{"Name":"ineffassign","Enabled":true,"EnabledByDefault":true},{"Name":"dupl"},{"Name":"goconst"},{"Name":"deadcode","Enabled":true,"EnabledByDefault":true},{"Name":"gocyclo"},{"Name":"typecheck","Enabled":true,"EnabledByDefault":true},{"Name":"gofmt"},{"Name":"goimports"},{"Name":"maligned"},{"Name":"depguard"},{"Name":"misspell"},{"Name":"lll"},{"Name":"unparam"},{"Name":"nakedret"},{"Name":"prealloc"},{"Name":"scopelint"},{"Name":"gocritic"},{"Name":"gochecknoinits"},{"Name":"gochecknoglobals"}]}}
```

However, if I invoke with the final path shown in the debug log, I get this:
```
$ golangci-lint run --fast --out-format json              /src/gonum.org/v1/exp/layout/barneshut/.golangcilint-ecrtj8
ERRO [runner/typecheck] typechecking error: unknown import path "gonum.org/v1/exp/layout/barneshut/.golangcilint-ecrtj8": cannot find package 
{"Issues":[],"Report":{"Linters":[{"Name":"govet","Enabled":true,"EnabledByDefault":true},{"Name":"errcheck","Enabled":true,"EnabledByDefault":true},{"Name":"golint"},{"Name":"staticcheck","EnabledByDefault":true},{"Name":"unused","EnabledByDefault":true},{"Name":"gosimple","EnabledByDefault":true},{"Name":"stylecheck"},{"Name":"gosec"},{"Name":"structcheck","Enabled":true,"EnabledByDefault":true},{"Name":"varcheck","Enabled":true,"EnabledByDefault":true},{"Name":"interfacer"},{"Name":"unconvert"},{"Name":"ineffassign","Enabled":true,"EnabledByDefault":true},{"Name":"dupl"},{"Name":"goconst"},{"Name":"deadcode","Enabled":true,"EnabledByDefault":true},{"Name":"gocyclo"},{"Name":"typecheck","Enabled":true,"EnabledByDefault":true},{"Name":"gofmt"},{"Name":"goimports"},{"Name":"maligned"},{"Name":"depguard"},{"Name":"misspell"},{"Name":"lll"},{"Name":"unparam"},{"Name":"nakedret"},{"Name":"prealloc"},{"Name":"scopelint"},{"Name":"gocritic"},{"Name":"gochecknoinits"},{"Name":"gochecknoglobals"}],"Error":"typechecking error: unknown import path \"gonum.org/v1/exp/layout/barneshut/.golangcilint-ecrtj8\": cannot find package"}}
```

So I suspect that the linter executable is failing because it is passed an invalid path, but the stderr output is being suppressed by SublimeLinter and there is no stdout.

**Comment by braver** [comment]
@cixtor Perhaps you can be of help here?

**Comment by kaste** [comment]
Ideally, the plugin would catch `stderr` too. Consider implementing `on_stderr(self, stderr)` for that. If you use the standard `_communicate` interface, SL should then split stdout and stderr, and will only pass `stdout` to e.g. `find_errors`.

**Comment by kortschak** [comment]
I have figured out what the cause of the error is. I have `GO111MODULE=on`. This apparently changes the behaviour of golangci-lint is its ability handle the additional fake path that is created by the plugin.

**Comment by cixtor** [comment]
Thank you for the bug report.

Preliminarily, I can see that the JSON output via `/dev/stdout` contains one warning _“govet: unreachable code (line 89, column 4)”_ but you don’t seem to be able to see that warning in the editor. I’ll investigate this first, and release a patch to address the issue. Then I will investigate what’s the problem with Go Modules.

I’ll comment here again when it is ready.

**Comment by kortschak** [comment]
The first problem is caused by the second problem. With `GO111MODULE=off` everything works as expected, but with it `on`, the linter executable returns the error in the last `<pre>` block in the original comment:
```
ERRO [runner/typecheck] typechecking error: unknown import path "gonum.org/v1/exp/layout/barneshut/.golangcilint-ecrtj8": cannot find package 
```

So, looking into modules first is probably a better approach.

**Comment by cixtor** [comment]
@kortschak I’ve spent some time investigating this issue.

The only way I can reproduce the same error is by forcing a failure in the symlink of the Go files into the temporary directory, or by referencing a Go module without initializing. I’ll keep investigating the error during the day after work hours, but if I am unable to reproduce the issue I will just add a [warning the same way I did with the canonical import paths](https://github.com/SublimeLinter/SublimeLinter-golangcilint/blob/d8d7ae9f7756464321dd9f54bc49c686fd5c165b/linter.py#L196-L231).

A temporary solution is to set `lint_mode` to anything but “background”, this is the same solution I recommend for people using canonical import paths. When lint mode is set to “load_save”, “manual”, or “save” the linter plugin executes `golangci-lint` against the real Go files rather than the symlinks created in the temporary directory. You’ll have to save the file every time you want to execute the linter though.

Please don’t use background lint mode for now, at least until I can find a good solution to both problems _(canonical import paths, and non initialized go modules)_.

**Comment by kortschak** [comment]
I see the failure on our gonum.org/v1/... codebase which obviously has a canonical import, but I also see with it my github.com/kortschak packages (all with init'd modules).

In manual, save and load_save" I similarly get no results:
```
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:253  Delay linting 'wol.go' for 0.0s
SublimeLinter: linter.py:970          golangcilint: checking lint mode 'load_save' vs lint reason 'on_save'
SublimeLinter: #8 linter.py:987       golangcilint: linting 'wol.go'
SublimeLinter: #8 linter.py:1462      Running ...

  /home/daniel/src/github.com/kortschak/wol  (working dir)
  $ /home/daniel/bin/golangci-lint run --fast --out-format json

SublimeLinter: #8 linter.py:1060      golangcilint: no output
SublimeLinter: sublime_linter.py:507  Linting 'wol.go' took 0.07s
```

Here is my go versions and env:
```
~ $ go version
go version go1.12.1 linux/amd64
~ $ go env
GOARCH="amd64"
GOBIN="..../bin"
GOCACHE="..../.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="...."
GOPROXY=""
GORACE=""
GOROOT="..../go"
GOTMPDIR=""
GOTOOLDIR="..../go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build328662982=/tmp/go-build -gno-record-gcc-switches"
```

I don't have an unusual Go set-up, so I don't understand what i making it impossible to reproduce this. Can you let me know what versions you are using and what OS?

**Comment by cixtor** [comment]
I am also using **go1.12.1** but on macOS.

I’ve cloned your repository [kortschak/wol](https://github.com/kortschak/wol), and made a small modification to trigger the linter, it accurately showed some warnings as you can see in the GIF below. I tested with both lint_mode “background” and “load_save”.

Can you please do the same, and see if the three warnings are highlighted? If the error that golangci-lint is sending to /dev/stderr is still present even with “load_save” then we can be sure that the problem is not the temporary directory, because the plugin only creates one when using “background”. Something else must be affecting the results. I’ll investigate this more carefully once I finished my shift today and go home.

![2019-04-01 14 20 39](https://user-images.githubusercontent.com/1933999/55360703-081f4d80-548a-11e9-8544-732363e3e08d.gif)

**Comment by kortschak** [comment]
I have done this and still do not see the warnings. I have also tried a change that should be picked up by govet without breaking compilation (which the change above does), i.e. adding a return after the last return (this is found if `GO111MODULE=off`).

**Comment by kortschak** [comment]
OK. I have an answer here. I set `util.STREAM_BOTH` in the golangcilint plugin to see what the problem was. It reports
```
SublimeLinter: #2 linter.py:677       WARNING: golangcilint output:
level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load program with go/packages: couldn't exec 'go [list -e -json -compiled -test=true -export=true -deps=true -find=false -- ./...]': exec: \"go\": executable file not found in $PATH *exec.Error"
```
With this knowledge, I can see that I was conflating starting `subl` with `GO111MODULE=on` with starting it with my shells env which has a `$PATH` including my `go`. Add the relevant path to `"paths": {"linux": []}` does not fix this, and I don't see a way to tell `subl` to add a path.

**Comment by kortschak** [comment]
Digging further, I can see that the `"paths"."linux"` array does get handled by the linter plugin, but the environ is not passed on to the linter executable. This means that though all of the SublimeLinter code knows where things can be found, but `golangci-lint` does not if they are not in the `$PATH` of the invoking environment as is the case on this machine.

**Comment by kortschak** [comment]
Correcting myself. It turns out that the new `_communicate` *does not* get the `paths` information since `get_environment` *does not* look at the settings except via the `env` key. Adding a call to `util.create_environment` into the `ChainMap` call does add this, but now we get a new failure.

```
level=warning msg="Failed to discover go env: failed to run 'go env': exit status 1"
level=error msg="Running error: context loading failed: failed to load program with go/packages: could not determine GOARCH and Go compiler"
```

See golangci/golangci-lint#397 for this.

**Comment by kortschak** [comment]
Is there any update on this? Specifically, how to ensure that the paths are passed to the linter executable.

**Comment by cixtor** [comment]
> Is there any update on this?

Sorry, no. I was not working on this at all. I thought your pull-request _—which was already merged and released—_ was enough to address this issue. I understand that the patch simply added a warning to the console when the environment variable is not accessible, but knowing how premature support for Go Modules is, I figured it was enough for now.

This week, I started working on a project that’s making use of Go Modules. I’ll use this as an opportunity to investigate the issue a bit more, and offer a solution as soon as possible. I am tied with other projects, so I cannot give an estimation of how long it will take me to release an update.

**Comment by cixtor** [comment]
> Is there any update on this?

Sorry, no. I was not working on this at all. I thought your pull-request _—which was already merged and released—_ was enough to address this issue. I understand that the patch simply added a warning to the console when the environment variable is not accessible, but knowing how premature support for Go Modules is, I figured it was enough for now.

This week, I started working on a project that’s making use of Go Modules. I’ll use this as an opportunity to investigate the issue a bit more, and offer a solution as soon as possible. I am tied with other projects, so I cannot give an estimation of how long it will take me to release an update.

---

**Edit:** Out of curiosity, @kortschak can you clarify this part a bit more:

> […] This means that all of the SublimeLinter code knows where things can be found, but golangci-lint does not if they are not in the $PATH of the invoking environment as is the case on this machine.

I wonder if you can solve this problem by adding that to $PATH since that’s the proper place to have binary files. I don’t understand very well what’s in conflict here. A few minutes ago I opened a project that’s using Go Modules, and the linter was able to show the warnings just fine, so I’m not sure if we actually need to modify the code to support a non-standard environment when you can fix the programming environment instead.

**Comment by kortschak** [comment]
Thanks.

>I wonder if you can solve this problem by adding that to $PATH since that’s the proper place to have binary files.

It is in $PATH. I place my go source tree in ~/go and add ~/go/bin to my $PATH. I regularly hack on the compiler and runtime, so this in important. The conflict happens because the env that is passed to sublime text via the GUI is deficient _cf._ the env passed from the CLI. This is presumably why there are configuration slots for adding $PATH information in SublimeLinter. This configurable $PATH information is not passed correctly to the linter executable.

To be clear, SublimeLinter works correctly when started from the CLI, but not from the GUI.

>A few minutes ago I opened a project that’s using Go Modules, and the linter was able to show the warnings just fine, so I’m not sure if we actually need to modify the code to support a non-standard environment when you can fix the programming environment instead.

I'd say that you'll keep seeing issues filed like this if this is not fixed. People rightly expect that a configuration that's [pointed to in the documentation](https://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#adding-to-the-paths-setting) should work.

**Comment by kaste** [comment]
The diff between starting Sublime from the GUI vs Terminal is basically a Sublime bug we hoped Sublime will solve. We have https://github.com/SublimeLinter/SublimeLinter/pull/1509 which *should* solve it as well. 

Within SublimeLinter, we have the `paths` setting which is only used for so called `which` calls. Whatever is set here doesn't effect the `ENV` at all. (We actually inherited this setting from the past, and hoped to deprecate it.)

Each linter on the other side has the `env` setting used while executing the linter. (It inherits the process env of Sublime.)

Now, you see this is a 'historical' mess. Should we pull #1509? Should we use the global 'paths' and merge it with the linter's 'env'? Is this a documentation thing after all, or something that should be handled with code?

(Main problem is probably that @braver and I don't have these issues, so we cannot reproduce and evaluate the solutions.)

**Comment by braver** [comment]
Sublime will actually get your `env` from your login shell, but it times out after about a second and some shells can't manage it quick enough. That's were most env-switching solutions and virtual environments and what not go wrong, and I have a feeling some shells simply aren't fast enough. Like @kaste says I don't have those problems, nor any experience with setups where they might occur. Also, Sublime (and any other desktop application) gets a different `env` to start with then your terminal shell, unless you start it from the terminal. SublimeLinter v3 and older used to have "solutions" for that, but those solutions came with more issues than we have now. Also, you need to have to problem to know it has been solved, and we simply don't have maintainers with the problem that we want to solve here. And it's not just a SublimeLinter problem, it's the same anywhere packages want to interface with command line tools. And the situation is the same there as well: not enough people with the `env` problems contribute to the community in a way that moves the entire thing forward in a a good way. In the end maintainers (of packages, but also the developers working on Sublime Text itself) are mostly guessing about the problems people are having and what solutions might do.

**Comment by cixtor** [comment]
Yes, I agree with @kaste and @braver.

I am happy to help, and would like to provide a solution as soon as possible, but I am unable to reproduce the problem described in this issue. I have launched SublimeText using `subl` _(the command line tool)_ and the GUI, and in both cases the linter works as expected, both with projects using Go modules and projects using the old GOPATH setup.

I understand that @kortschak is using Linux, maybe that’s it. I am on macOS, maybe the setup on Linux differs significantly to cause problems with the environment variables. I’ll spend some time this week setting up a Linux virtual machine, and will try to reproduce the issue.

**Comment by kortschak** [comment]
The issue is likely to be because I locate my Go tree not in the `$PATH` that is exported by the GUI. If you install Go in ~/go, with the `go` executable in ~/go/bin (as stated in https://github.com/SublimeLinter/SublimeLinter/issues/1586#issuecomment-485562897), and not in wherever it is that the macOS package places it, do you still fail to reproduce this?

>Sublime will actually get your `env` from your login shell

Is this documented somewhere? From which login shell? The GUI and virtual terminal shells are different.

**Comment by kortschak** [comment]
BTW I'd be happy to try hacking on this to find a solution, but I don't see how to install the package without using PackageControl; if I clone the repo to ~/.config/sublime-text-3/Packages/User it does not work, and attempting to open Settings/Key Bindings results in errors like this:

"The settings file "res://Packages/SublimeLinter/keymaps/Default (Linux).sublime-keymap" could not be opened"

I was hacking on it before to send the stderr PR, but that involved writing inside the sublime-package zip file, which is not an ideal method of fix development.

Are there contributor instructions? I don't see any.

**Comment by cixtor** [comment]
> BTW I'd be happy to try hacking on this to find a solution, but I don't see how to install the package without using PackageControl […]

@kortschak if you are referring to the SublimeLinter-golangcilint plugin, you can use this Makefile [1]. You can clone the repository anywhere in your computer, make changes to the “linter.py” file, then execute `make`, and the Makefile will override the installed package with the one you are currently modifying.

You’ll have to adapt it to work on Linux though, using `~/.config/sublime-text-3/` instead of `~/Library/Application Support/Sublime Text 3/`. And you’ll also need to restart SublimeText every time you execute the command to load the new code _(minor inconvenience that I haven’t found a solution for)_. I think you can also put the cloned repository in `~/.config/sublime-text-3/Installed Packages/` and it will just work, it doesn’t have to be a Zip archive as far as I know.

[1] https://github.com/SublimeLinter/SublimeLinter-golangcilint/blob/master/Makefile

**Comment by kortschak** [comment]
No, I'm referring to the both the SublimeLinter and SublimeLinter-golangcilint plugins. I have tried placing the git clone in Installed Packages and in Packages/User (both of these work for other packages I have installed) but neither works.

**Comment by braver** [comment]
You can put packages you want to work on in Packages. “Installed Packages” is for packages installed via package control, “Packages/User” is the user package, i.e. it’s one level too deep.

> Is this documented somewhere? 

I believe the command to read the env is logged in the console.

**Comment by kortschak** [comment]
Thanks on both counts. Interestingly, the `$PATH` is correctly reported there, so it seems it's down to properly exporting the env to the child.

**Comment by kaste** [comment]
@cixtor @kortschak You don't need a Makefile, and you don't need to restart Sublime on every change. We hot-reload. For the actual golangcilint plugin, SublimeLinter will reload the plugin whenever you save 'linter.py'. 

For the core SublimeLinter, you get reload on save for the top-level .py files (the controller and the views), if you edit files in subdirs you can execute the 'Reload SublimeLinter' command from the command palette. 

Usually, just 'git clone' plugins into the 'Packages' folder. (T.i. no need to uninstall prior to that!)

**Comment by kortschak** [comment]
Yes. I have that working now and I was expecting hot reload since that's how everything else I use works with ST3. I'll take a look at the actual problem here over the next few days.

**Comment by kortschak** [comment]
After a small amount of digging, I can see the issue very clearly now. It may warrant a documentation change/addition, but other people with the same problem can find the answer here is that doesn't happen.

I generally work on the command line and so set my env vars via `.bashrc`. Those vars obviously don't get passed to GUI applications. Setting the `$PATH` addition in `.profile`, and so making them available to GUI applications fixes this problem for both the graphical and command line environments. (It also explains why the macOS users here probably didn't see it - being likely more often using the GUI-relevant configuration files).

**Comment by palytoxin** [comment]
hi, @kortschak 
I encountered the same problem, I try to add PATH env to .profile, but the problem is the same.
What did you do about this problem?

my machine is Linux mint
and go env
```
home> go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yan/.cache/go-build"
GOENV="/home/yan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yan/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/home/yan/.asdf/installs/golang/1.14/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/yan/.asdf/installs/golang/1.14/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build811309793=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by kortschak** [comment]
I have `export PATH=~/bin:$PATH` in `.profile`. In the Sublime Linter settings, I don't have anything other than this in the user settings:
```
// SublimeLinter Settings - User
{
	"debug": true,
    "paths": {
        "linux": ["~/go/bin"],
    },
}
```

**Comment by palytoxin** [comment]
uhh... It doesn't work for me.
linuxmint 19.3
sublime text 3.2.2 build 3211
sublime linter v4.15.0
sublimelinter-golangcilint v2.0.0
golangci-lint  v1.25.1-0.20200422234654-0fb48ad5f550
```
  /home/yan/code/opendata  (working dir)
  $ /home/yan/go/bin/golangci-lint run --fast --out-format tab /home/yan/code/opendata/models

SublimeLinter: #6 linter.py:788       Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #6 linter.py:1196      golangcilint: no output
SublimeLinter: sublime_linter.py:572  Linting 'dataset.go' took 6.65s
```

**Comment by cixtor** [comment]
@palytoxin can you please open a Terminal session and execute the following commands then share the output here?

```shell
cd /home/yan/code/opendata || exit
/home/yan/go/bin/golangci-lint run --fast --out-format tab /home/yan/code/opendata/models
```

**Comment by palytoxin** [comment]
![image](https://user-images.githubusercontent.com/1829328/82641365-d0033d00-9c3e-11ea-82d5-1de377469bef.png)

there is show some mistakes in terminal

**Comment by cixtor** [comment]
@palytoxin I think you are misunderstanding the output you are seeing.

It seems like you think the warnings (highlighted in yellow) and errors (highlighted in red) are part of your code base but they are not. They are all exceptions in the execution of golangci-lint because 1) it was unable to execute “goanalysis_metalinter” and 2) it was unable to execute “unused”, both warnings led to the fatal error that says _“buildssa: analysis skipped”_ which basically translates to _“Hey! The code we are trying to analyze is so broken we cannot even lint”_.

Because these warnings and errors are all part of golangci-lint rather than one of their linters, the output is sent to `/dev/stderr` rather than `/dev/stdout` so the SublimeText plugin doesn’t even know what is happening.

You may ask, why is `/dev/stderr` not treated as fatal errors by the SublimeText plugin? They are, there is a mechanism that displays a message or alert _(I don’t remember which one)_ when the plugin fails, but this only works if the output is in JSON format, that is why the command has `--out-format json` but clearly the output you have is not in JSON, so that’s why you cannot see these errors in SublimeText.

This was a solved problem in the original version of the plugin I wrote, but we ended up merging a very simplified version of the code a while ago that removed many of the safety measures I had predicted would happen, like this one. I don’t want to get into that discussion again so I will only say this…

The warnings and errors should be printed in JSON format to satisfy the value of `--out-format`, but this is something we cannot fix from the SublimeText plugin. Someone, maybe you, will have to [report this as a feature request in the golangci-lint repository](https://github.com/golangci/golangci-lint/issues). We do not need to change anything in the plugin. Once the golangci-lint developers have implemented a better error reporter the SublimeText plugin will magically work again.

I hope my explanation was clear. Let me know if you’d like more details.

**Comment by palytoxin** [comment]
Oh, I see. I asked a stupid question.
At first, I misunderstood golangcilint's output, it can't output compiler errors. like my problem above, the wrong number of return values.

Maybe it's the golangcilint problem.
thx a lot

**Comment by cixtor** [comment]
[There’s no such thing as a stupid question as long as it ends in a question mark](https://en.wikipedia.org/wiki/No_such_thing_as_a_stupid_question).

I don’t come across these errors very often but I can see myself falling in the same trap, so I hope you can talk to **Denis Isaev** _—the author of golangci-lint—_ to implement a graceful fatal error catcher. You can reach him on the [Gophers Slack group](https://app.slack.com/client/T029RQSE6/CS0TBRKPC), if you haven’t joined [here is an invitation link](https://invite.slack.golangbridge.org/).
