### ISSUE TITLE
Replace our no-response bot?

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1619]
The no-response is lame bc it re-opens issues which should be a manual action. Also adding/re-adding the awaiting response label is lame.

We could just fork it?

- Listen for 'question and setup' issues. (Or generally 'support' tickets.) (We never close other tickets automatically.)

- Close after 14 or so days inactivity with a nice message. 

- No step 3.

(The bot we have is open source, so we can fork it, remove half the code, and be done.)

**Comment by braver** [comment]
Sure, I'm not against more automation here. This is just something I picked up from a different project and it's better than nothing. 

I do like the explicit label, because it announces that the reporter has to take action for it to move forward. But 'question and setup' is also a good candidate.

I have it on a bunch of plugin repos as well, some get a lot of questions or incomplete reports and it's nice that they're cleaned up automatically as well. As you know, I'm lazy, so I don't feel like going around switching out the bot elsewhere because basically it serves its main purpose.

**Comment by cyrus303** [comment]
hello, can i work on this ?

**Comment by kaste** [comment]
Go for it!

**Comment by kaste** [comment]
Since we really dropped below any low volume, we don't need any bots.
