### ISSUE TITLE
Wrong working directory on nested local eslint installs (breaks eslint@6)

### ISSUE THREAD

**Issue by nikku** [SublimeLinter/SublimeLinter#1626]
In my mono-repository setup I have the following structure:

```
bar
  - .eslintrc
  - package.json < installs eslint, eslint-plugin-mocha
  - foo.js < file to be linted
package.json < parent package.json, in mono-repository setup
```

Linting via SublimeLinter-eslint uses the project root as the working directory despite the fact that `eslint` is located in the sub-directory. Because of that eslint fails to locate plug-ins, installed in the sub-directory, next to the eslint installation:

```
SublimeLinter: #11 linter.py:1478     Running ...

  {{DIR}}  (working dir)
  $ cat bar/foo.js | {{DIR}}/bar/node_modules/.bin/eslint --format json --stdin --stdin-filename {{DIR}}/bar/foo.js

SublimeLinter: #11 linter.py:49       ERROR: 

Oops! Something went wrong! :(

ESLint: 6.0.1.

ESLint couldn't find the plugin "eslint-plugin-mocha".

(The package "eslint-plugin-mocha" was not found when loaded as a Node module from the directory "{{DIR}}".)
```

__Expected Behavior__

The directory into which `eslint` is installed (locally) is used as a `cwd` when running the command.

__Reproduce__

I've created [a example setup](https://github.com/nikku/sublime-eslint-test/) that shows the issue. To reproduce, clone and install it

```
git clone git@github.com:nikku/sublime-eslint-test.git
(cd sublime-eslint-test/bar && npm install
```

Then open `sublime-eslint-test` in Sublime Text, navigate to `sublime-eslint-test/bar/foo.js` in Sublime Text.

**Comment by kaste** [comment]
Hm, thanks for the reproduction. Well, why does eslint behave like that 😭 ?

**Comment by kaste** [comment]
Honestly, this is new behavior of eslint, isn't it?

**Comment by nikku** [comment]
You are right, it works with `eslint@5`. 

It seems like given a file `{CWD}/bar/foo.js` won't search for installed plug-ins in all parent directories (`{CWD}/bar`, `{CWD}`) but only up to the directory `eslint` is installed itself. This breaking change is [documented here](https://eslint.org/docs/user-guide/migrating-to-6.0.0#-plugins-and-shareable-configs-are-no-longer-affected-by-eslints-location).

So a workaround for this behavior is to go back to `eslint@5` for now. 

A long term solution would probably be to make `{CWD}` the directory in which `eslint` got installed (if installed locally).

**Comment by allhaker** [comment]
Running into the same issue here.

Except I have a whole directory of a dozen projects at the same time. Nevertheless, eslint tries to find deps in the root of my current working directory.

Is that even fixable on SublimeLinter side?

**Comment by kaste** [comment]
That's a super-breaking change. They break global installs totally. (There is actually a totally valid usage pattern to have a global all-included eslint install.)

> With the new design, ESLint will load all plugins and formatters relative to the *project root*. By default, the project root is simply the CWD of the running process.

(from the RFC https://github.com/eslint/rfcs/pull/7)

That's a super surprising interpretation of *project root*. Naively anyone would say the project root is the location of package.json. In an IDE the project root would be the top folder you're currently editing. 

In a way, they implicitly state, that @nikku is doing it wrong because all tools like eslint should be installed in the root of a monorepo project (which is indeed a recommendation but only that: a recommendation). Otherwise, not just for SublimeLinter, just on the command line you can't invoke eslint anymore - say from a script. You have to `cd` in the subfolders.

**Comment by braver** [comment]
Wow 😯

**Comment by nikku** [comment]
> Otherwise, not just for SublimeLinter, just on the command line you can't invoke eslint anymore - say from a script. You have to cd in the subfolders.

Would that be something that can be supported in SublimeLinter? Do you see an issue with that behavior? There exists a lot of logic already to find the directory has `npm install`(ed) eslint. We'd simply need to `cd` into that directory before invoking `eslint` rather than invoking `eslint` from a global path.

**Comment by kaste** [comment]
Well, we need to compute the *project root*. I wonder why eslint can't compute the project root and just uses cwd as the default. Does that mean it isn't computable and we have to find a 80% solution? (I never used lerna nor yarn workspaces. I have actually no idea what serious problems eslint had to solve here.)

We then have to find the real executable given that project root.

**Comment by nikku** [comment]
> Well, we need to compute the project root. 

Why is this an issue? The project root from eslint's perspective is the directory in which eslint is installed. That makes total sense. The project root from SublimeLinters perspective is what exactly? Given my structure with multiple package jsons SublimeLinter will deduce that the outermost directory with a package JSON is the project root. I believe that is not the right assumption.

**Comment by nikku** [comment]
If you provide me with some pointers where and how sublime linter computes the CWD (if it gives plug-ins control over that) I'm happy to look into the issue and attempt a PR.

**Comment by kaste** [comment]
The cwd SublimeLinter is using by default is just the top folder you have currently open (in that window). That's a typical definition of *project root* inside an IDE. (And it actually works for all linter plugins.) 

You could also just work around that way: Either you start Sublime via `subl .` while being in a specific subfolder, or you add that (sub-)folder to the project. (If you do `subl .` you by default only have one 'open' folder, but using project files you can have multiple root folders. E.g. setting folders to `['root/backend', 'root/frontend', 'root']` would iirc pick 'root/backend' as the cwd if you're editing a backend file etc.)

As I understand the eslint change, the project root is NOT the dir where eslint is installed. (Okay, actually eslint is installed in `{dir}/node_modules/bin/eslint`.) If it were, eslint could compute this root easily bc its just two or three levels up from the file it currently executes. From my understanding, the project root is where eslint is *declared* in a package.json as a dep or devDep (but probably not peerDep). But since we also must find an executable, we must then traverse up looking for the actual eslint install.

What we have right now, is that we actually don't look for any package.json files for the happy path. We just traverse up looking for an eslint binary and we're done. So what we have right now is we just look for a single value `executable`, and we need to change that and find a pair `(executable, project_root)`

Overall, the code is here: https://github.com/SublimeLinter/SublimeLinter/blob/64cde020583f0e7afc0059048272f1a1a8d1787e/lint/base_linter/node_linter.py#L103-L166

The code change is probably mildly simple. The function returns either None or the executable. We wouldn't need to change this signature immediately, instead we just set a new context variable like `self.context['project_root'] = found_project_root` and then later we consider this variable when computing the working dir.

**Comment by kaste** [comment]
Oh, we need some bike-shedding about the name 'project_root' bc 'project', 'project_path' are used names with the typical Sublime/IDE meaning.

**Comment by nikku** [comment]
Unfortunately I found myself unable to build a fix. I'm not an profound python developer, that may be part of the problem :worried:. Is there any python developers in the userbase that uses eslint (and JavaScript) that can help?

**Comment by kaste** [comment]
I have stashed something while investigating and writing the above comment. The cumbersome part will be writing the tests I guess.

**Comment by kaste** [comment]
To make it work reliable we need to research for which linters the binary name doesn't match the package name. 😢 (Generally, I would like to make this `project_root` available to all other node linters as well (e.g. sass, flow, cssblah...). I don't want to hack it just for eslint.)

**Comment by kaste** [comment]
@braver Is there a script to clone all linter plugins we know of. (And keep them up-to-date?) Not bash, x-platform. 😬 

@anyone At least: clone and pull the whole org?

**Comment by braver** [comment]
Yeah, our package control repo had a Python script to do so.

**Comment by KevinSheedy** [comment]
Same issue here. I've two npm projects inside a `/container` folder:
```
/container
  /react-app-one
    /package.json
    /.eslintrc.js
  /react-app-two
    /package.json
    /.eslintrc.js
```

Previously, I could add `/container` to Sublime and linting worked.
Now to get linting working, I have to add `/react-app-one` and `/react-app-two` to sublime but not `/container`.

**Comment by kaste** [comment]
You can add container but it must come after the other ones.

**Comment by KevinSheedy** [comment]
> You can add container but it must come after the other ones.

Adding the subfolders and the container causes all the files to appear twice when searching with `COMMAND-P`

**Comment by kaste** [comment]
That technically a Sublime bug 😁 🙄

**Comment by kaste** [comment]
@HusamIbrahim did an amazing job here 👏
