### ISSUE TITLE
How to activate preferred linter if language/scope has more than one possible linter

### ISSUE THREAD

**Issue by cpruitt** [SublimeLinter/SublimeLinter#1629]
I spent a little time searching docs/issues for this information but I'm not sure I know the right terminology so I'm sorry if I missed it!

## Summary

Given a language (e.g. Ruby) with two linter plugins (e.g. Rubocop and StandardRB) I'm looking for a way to intelligently identify which to use, preferably based on the presence / absence of corresponding config files.

## More Details

I'm interested in finding a way to more intelligently switch between different linters that are used for the same language / scope without relying on `.sublime-project` files or manually enabling/disabling linters.

For example:

For Ruby, I prefer that `standard` (https://github.com/testdouble/standard) be my default linter (no contrib plugin for this yet, just a private plugin), but many Ruby projects use Rubocop. The two follow different rules and have different philosophies, so it's not uncommon, if both linters are active, for a file to get stuck in a situation where the two conflict. I can manually enable/disable as needed, but that isn't super convenient and makes it hard to work on two projects that use different linters (e.g a Standard linted project with a Rubocop linted dependencey). I can enable/disable with settings in a `.sublime-project` but that wont work if opening up a folder without using a project file (e.g. `subl ~/path/to/some/project`).

What I'm interested in is a way to enable/disable a given plugin based on some criteria such as the presence of files in the first open folder. So, if the first open folder contains a `.rubocop.yml` then rubocop would be used. If the folder contains `.standard.yml` then standard would be used.

I realize that given all the various linters available, mantaining an exhaustive master list of what linter should be active, and why, is not practical. I'm curious, however if there is a way to treat the `SublimeLinter.linters.<linter>.disable` setting in a more dynamic way and allow some other package's code to have a say in determining whether a given linter should be active or not. That way another plugin (say `SublimeLinter-contrib-ruby-linter-switcher-thingy`) could be used to do the decision making.
  
I'm also open to any other recommended solution for having linters play nice.

**Comment by kaste** [comment]
Now, for `standard`there are no config files bc everything is standard. So this will probably difficult or idiosyncratic just works for me. `rubocop` is probably interesting to bake it in if it is more or less a standard to have the config in the project, otherwise rubocop looks everywhere for it. So for rubopcop, `disable_if_no_project_config` could be doable. 

You can also just write an addon. You listen for `on_activated_async(view)` events. Then you decide which linter should run on this view. After all, you basically set `view.settings.set('SublimeLinter.linters.rubocop.disable', True|False)`. There is also an addon `SublimeLinter-addon-toggler` which lets you disable/enable linter not automatically but per command palette.

I actually prefer sublime-project files. And I would suggest you write a script or plugin so that `subl <folder>` actually opens that folder with a project associated automatically. That's mostly what I have. So I have the convenient `subl .` experience with automatic projects behind. Esp. bc then I also have the workspace(?) files. The thingy where Sublime stores all window state, e.g. the panel heights, autocomplete stuff, fuzzy matching abbreviations.

Let us know if you have any questions.

**Comment by cpruitt** [comment]
Thank you @kaste for the quick response! 🙂 You suggested a few different options there so I'll dig into it a little bit and see what I can come up with. One point of clarification that I might not have been clean on is that I'm hoping to resolve conflicting linter results between `rubocop` and `standardrb` (Ruby linter https://github.com/testdouble/standard) not the `standard` JS linter. `standardrb` does make use of a `.standard.yml` which **might** be present in the project (or a parent directory).

I have a linter plugin I threw together for `standardrb` and am considering cleaning it up and contributing it but would like it to play nice alongside rubocop (and vice-versa). It's been a bit rough around the edges trying to have both linters enabled when I'm not working with project files. Given that it might end up being used by others I'd like to not rely on projects if possible. Your tip for automatically creating projects sounds nice and might be something I look into but it wouldn't work out of the box for another user with a different workflow, so I'll see what else I can do first.

In a perfect world I think this would have behavior something like:

- If a project is opened use the project settings for enabled linter
- If a folder is opened without a project (or a project isn't explicit) check for a known config file and activate linter accordingly
- As a last resort use a default linter (I suppose the current enable/disable in global config would be in effect at that point)

From what I see, it seems like `view.settings.set('SublimeLinter.linters.rubocop.disable', True|False)` might be the most promising. I'd just like to do that in a way that doesn't inadvertently stomp on the existing rubocop plugin.

**Comment by kaste** [comment]
I think you want a simple 'prefer-standardrb' addon. So you look for a 'rubocop.yml' and then turn rubocop on or off. If you turn it on, you also turn standardrb off.

Generally, 'disabled' has three states `True|False|Nonenilnull`. You should only change the configuration if it is 'None' bc otherwise the user has set something already.

A tip:

```
import sys
'SublimeLinter-rubocop' in sys.modules  # rubocop installed
```

You can't change the configuration of the *other* linter in your standardrb plugin btw bc both linters run in parallel. You have to decide `on_activated_async`.

**Comment by cpruitt** [comment]
Ok, perfect, I think that gets me going in the right direction. Many thanks! 🙇🏻‍♂️

**Comment by kaste** [comment]
Forgot tho close this one.
