### ISSUE TITLE
The performance issue

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1662]
Let's talk about performance. In the following, I measure (as always) with an mediocre laptop in battery mode. We measure propagating errors, i.e. the runtime of the `group_by_filename_and_update` fn (in `sublime_linter.py`) generally using `util.print_runtime`.

v4.13 as the bottom line. 

```
A: (panel closed, active file has 4 errors)
0 errors across 0 files from annotations. 146 errors in the store
group_by_filename_and_update took 24ms [D]

0 errors across 0 files from flake8. 146 errors in the store
group_by_filename_and_update took 22ms [D]

8 errors across 5 files from mypy. 146 errors in the store
group_by_filename_and_update took 82ms [D]
```

```
B: (panel closed, active file has 52 errors)
0 errors across 0 files from annotations. 146 errors in the store
group_by_filename_and_update took 118ms [D]

0 errors across 0 files from flake8. 146 errors in the store
group_by_filename_and_update took 107ms [D]

58 errors across 5 files from mypy. 146 errors in the store
group_by_filename_and_update took 226ms [D]
```

```
C: (panel open, active file has 1 error)
0 errors across 0 files from annotations. 146 errors in the store
group_by_filename_and_update took 66ms [D]

0 errors across 0 files from flake8. 146 errors in the store
group_by_filename_and_update took 47ms [D]

68 errors across 29 files from mypy. 146 errors in the store
group_by_filename_and_update took 731ms [D]   <--- !
```

The code here does not block the UI, but it runs on the (shared) worker thread which means it blocks other plugins and essentially all "async" events to run.

A1 and A2 are often noops bc they don't add new errors; A3 is already an excess for just 8 errors (but across 5 files). For B, B1 and B2 even pay a cost just because count of errors of that file is bigger. All of B is above 100ms. C3 shows an excess.

Luckily this is all code we never optimized a single bit; admittedly we must aim for a 10x improvement.

**Comment by braver** [comment]
My problem is usually very slow NodeJS linters that access the file system every time they run to read a big config file. That really tends to hang up stuff. Although I must I run on a 🏎  of a laptop mostly and it's fine, or all my lag comes from a terribly slow network drive with a VPN in between and what not. 

For laughs you should (but probably can't anymore) run this test with SL3. That thing was really slow.

That said, I applaud this milestone. B can be better, C3 really is excessive. If there is headroom in the code because it was never optimized, I'd say go for it. But perhaps not go overboard, performance optimization can really hurt legibility and maintainability of code. But I suspect I don't have to tell you that :)
