### ISSUE TITLE
Hide context-menu "Lint this view"

### ISSUE THREAD

**Issue by olavk** [SublimeLinter/SublimeLinter#1672]
Please hide context-menu **"Lint this view"** when `"lint_mode": "background"`.
In this scenario that button does nothing. It uses up precious real-estate in the context menu.
I would do it myself but I don't know what the context-menu `is_visible` condition should be.
Thank you!

**Comment by braver** [comment]
Well, it should actually trigger a lint, if for whatever reason it didn't run. But I agree it doesn't need to be featured prominently in this case. The `is_visible` condition would be that the view settings report that at least one linter is registered for it, and "lint_mode" is not "background". Should be easy enough.

**Comment by kaste** [comment]
This is also a bit buggy right now bc the context menu is also populated for e.g. GitSavvy fancy interfaces (if you have e.g. annotations linter on). 

Note that this will also remove the command from the Command Palette though. Is this intended as well or should we make a new command?

**Comment by braver** [comment]
Well, I’m not 100% convinced that removing the command is a good idea. That is, if at least one linter is active for that view. It can create an unexpected “now it’s there... now it’s not” behavior. And even if you don’t necessarily need a command, should it not still be there just in case? 
I believe, but would have to check, that it’s possible for a user to override the context menu and remove the command he doesn’t need. So something dynamic and automatic would be nice, but maybe not necessary in most cases?

**Comment by kaste** [comment]
Can users also override Command Palette entries? Or can we only add/append commands?

The command in the Palette should always be visible imo.

**Comment by braver** [comment]
Well, specifically, users can override any file of an installed package. To override the context menu provided by us, you would create a file at `Packages/SublimeLinter/menus/Context.sublime-menu` and put something in there. Or make it empty. SublimeText will replace the file of the installed package with yours. I use that myself to remove some cruft from the sidebar context menu for instance. So in that sense, users of Sublime Text already have a lot of control over what is in what menu. 

It's not a hidden feature either, it's just how the customization-cascade works. But it's not something a lot of people know about or know how to use, and admittedly I had to remind myself how it works.

> The command in the Palette should always be visible imo. 

I agree, it's the main index of everything a package can do, and should hold everything that's available at a given moment.

So, if any user is really worried about the real estate of a given menu, he or she can do something about it without our help. The question here is, what is the right thing to do. Maybe removing the command from the context menu when it's not needed is a good idea and still easy enough to implement. I personally don't have strong opinions here, also because I don't believe people go through the context menu to do stuff (but I may be wrong... when I'm programming I'm not much of a mouser, but I know people who are unable to do anything via keyboard so perhaps I'm just really biased here).

**Comment by kaste** [comment]
Yeah okay, a package override... I hoped there is something easier just like for key bindings or theme extension. Package overrides are a bit dangerous without auditing these overrides.

**Comment by braver** [comment]
Oh sure. But overrides are a central part of how ST works, so if it’s just about one guy wanting one thing we don’t have to do anything really.

Anyway, that’s more words spent than it would take code write. This should be enough input for someone to make a PR. Or not 🤷🏼‍♂️

**Comment by olavk** [comment]
Ok thank you guys for the feedback. I got around to making a PR. I figured if it's that complicated to check for a proper condition, why not add a setting? I think it's fairly justified to have Context Menu items toggle-able.
https://github.com/SublimeLinter/SublimeLinter/pull/1674

**Comment by braver** [comment]
We shouldn’t add a setting here if we’re not going to something smart and dynamic. If we don’t find a smart approach that works for everyone, we don’t do anything. People can already remove the menu item if they want, as I explained. We should document how to do so. This way people will come to understand how Sublime works and will be able to customize other menu entries all by themselves.

**Comment by braver** [comment]
I just ran into an interesting case. When a linter is set to in background mode, it runs automatically, but only if the file itself has been changed. If for instance the linter config file was changed, you need a way to manually run the linter to update the results. So even then there is a very good reason for there to be a "lint this view" button. Hiding it in this case is bound to cause confusion.

**Comment by olavk** [comment]
Sure, even more reason to add a setting. All sorts of plugins add their own menu items. The setting should be added just out of courtesy. What kind of overhead would it add? I don't know. You guys are the maintainers. I'm fine, I'm using the override. Thanks for suggesting that, i wasn't aware
