### ISSUE TITLE
Sublime linter stops working after several minutes of usage

### ISSUE THREAD

**Issue by gejimayu** [SublimeLinter/SublimeLinter#1698]
This always happens after a few minutes of usage (5-10 minutes).

The status on the bar is showing "Linting..." but it never ends.

I need to restart the whole sublime to make it work again. But then it will stop working again.

Is anybody facing the same issue ?

**Comment by kaste** [comment]
Is it "just" that the status bar keeps showing the spinner, or does it completely stop linting. 

For the first option: I've noticed that too, but only sometimes, and usually when panels have focus, and then it heals itself when changing views, so it wasn't strictly high priority for me.

Second option: Please make sure to enable debug mode of course and see what it does actually.  Now, if everything works on our side 🤞, you should just have never ending processes e.g. visible in the Task Manager/Process Manager of your OS.  (These should be childs of the sublime process.)  I only ever saw this with a PHP linter in an old version.  When the processes never end, at some point the queue is full, and SublimeLinter would stop creating more processes (usually a good thing 😁).

**Comment by gejimayu** [comment]
it's the second option, it completely stops linting.
This is the log

> SublimeLinter: #151 linter.py:1120    eslint: linting 'index.js'
SublimeLinter: #151 linter.py:900     eslint: wanted executable is '/Users/gianfranco.fh/Documents/shopee_react_native/packages/bb8-lint/bin/lint.js'
SublimeLinter: #151 linter.py:1636    Running ...
SublimeLinter: sublime_linter.py:324  Delay linting 'index.js' for 0.41s
SublimeLinter: linter.py:1103         eslint: Checking lint mode 'background' vs lint reason 'on_modified'.  Ok.
SublimeLinter: sublime_linter.py:379  Friendly terminate: <pid 3396>, <pid 3461>, <pid 3475>

**Comment by kaste** [comment]
Okay, from the `Friendly terminate` you see that there are (at least) three processes not returning. They don't respond to a `SIGTERM` signal as well.  (Maybe they are interactive?)  We don't have atm a way to debug this, e.g. see the stdout/stderr received so far.  

You're using a custom `executable` here which is probably more buggy than the standard eslint tbh.  How is that executed actually because you only define a `*.js` file.  (You could also set it to an array instead `["path/to/node", "path/to/mylinter.js"]` to be sure what's going on.) Can you inspect the processes using your standard OS tools? (Task Manager whatever).  Can you force them to be killed?  Do they eat up your CPU?  Is it possible that they get into an interactive mode?  Do they dislike the SIGTERM, and ask you to confirm?  (In SublimeLinter global settings try setting `kill_old_processes` to `false`.)

**Comment by gejimayu** [comment]
it's too complicated, i decided to move to VS code. thank you for the help
