### ISSUE TITLE
Can't see gutter icons

### ISSUE THREAD

**Issue by adevart** [SublimeLinter/SublimeLinter#1704]
I installed the linter package and the SublimeLinter-tslint package for Typescript.
I can run the commands ok from the command palette and I have a context menu item to lint the view.
When I run these, the status bar shows tslint(ok) and the panel called Output:SublimeLinter shows "no lint results". The results are logged in the console output panel though.

I don't see any visual markers in the UI, either gutter or in the text. I tried setting the theme in settings, I tried changing the editor theme, I copied the gutter theme folders to the User folder, I tried setting the markup.error and warning color schemes in scope but no indicators in the UI show up.

Is the SublimeLinter output panel supposed to say "no lint results" and is this possibly making the gutter icons not show in the UI?

I'm using the latest version of Sublime (3.2.2) on Mac.

**Comment by kaste** [comment]
If the panel says no lint results and the status bar ok then not having gutter icons is consistent.

I assume you already have debug set to true because you see something logged to the console. If not what still is logged are actually errors, t.i. hard errors not usual lint. E.g. config errors etc. 

Whatever it is, you should post it here.

It is somewhat possible that your tslint formats its output in a way we don't expect, this would be clear if you have debug on though because it then logs all lines with a "no match for" or something similar worded.

**Comment by adevart** [comment]
This was due to the tslint version installed, older versions have a different output format.

https://github.com/SublimeLinter/SublimeLinter-tslint/issues/44
