### ISSUE TITLE
Golangcilint linter reports "cannot import absolute path" and doesn't work

### ISSUE THREAD

**Issue by dpedu** [SublimeLinter/SublimeLinter#1706]
I installed `SublimeLinter-golangcilint` today, and when it lints my code it reports:

```
SublimeLinter: linter.py:1103         golangcilint: Checking lint mode 'load_save' vs lint reason 'on_save'.  Ok.
SublimeLinter: #6 linter.py:1120      golangcilint: linting 'ipamdao.go'
SublimeLinter: #6 linter.py:1636      Running ...

  /Users/my/code  (working dir)
  $ /Users/dpedu/go/bin/golangci-lint run --fast --out-format tab /Users/my/code/path

SublimeLinter: #6 linter.py:786       WARNING: golangcilint output:
level=error msg="[runner/typecheck] typechecking error: import \"/Users/my/code/path\": cannot inort absolute path"

SublimeLinter: #6 linter.py:788       Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #6 linter.py:1196      golangcilint: no output
SublimeLinter: sublime_linter.py:575  Linting 'ipamdao.go' took 0.16s
```

**Comment by kaste** [comment]
Maybe @cixtor can help?

**Comment by kaste** [comment]
@dpedu Do you think that this is an error on our side?  Abs import paths are not allowed in go, but I don't know if the tooling *could* be doing something wrong here, or if you literally try to import basically a file path.

**Comment by dpedu** [comment]
I didn't have any absolute imports in my code, no. Just normal stdlib and a couple `domain.com/foo/bar` imports.

**Comment by kaste** [comment]
Okay, since you posted the debug stuff.  Can you replicate the message/error on the command line. Given the same working dir, and literally the same command?

**Comment by cixtor** [comment]
@dpedu `golangci-lint` fails when called against a folder rather than a file:

```
WORKS -> golangci-lint run --fast --out-format tab
FAILS -> golangci-lint run --fast --out-format tab /Users/my/code/path
WORKS -> golangci-lint run --fast --out-format tab /Users/my/code/path/ipamdao.go
```

I believe this was working in previous version of the SublimeLinter plugin. I believe the algorithm that I wrote to determine the target broke when we decided to merge [Pull-Request 3](https://github.com/SublimeLinter/SublimeLinter-golangcilint/pull/3) which was supposed to simplify my original code with something simple. Unfortunately, the code is now so simple that detecting if the editor triggered the linter against a folder rather than a file is not possible unless we make more changes.

The linter command is defined as follows:

```python
cmd = 'golangci-lint run --fast --out-format tab ${file_path}'
```

The correct execution would be either:

a. Linter runs when you preview a file, then: `[…] --output-format tab /path/to/file.go`
b. Linter runs when you open a file, then: `[…] --output-format tab /path/to/file.go`
c. Linter runs when you open a folder, then: `[…] --output-format tab`

However, for some reason, `${file_path}` was set to contain the folder where your Go files are located instead of an empty string. Because of this, the final command now has an extra parameter that confuses `golangci-lint` and triggers the error.

**Comment by kaste** [comment]
I also reviewed said PR, at that time and following their readme, golangcli-lint could run against directories. Quote:

> golangci-lint run dir1 dir2/... dir3/file1.go

If you omit the last arg, golangcli-lint basically expands it to `./...` which means the working dir recursively. 

Do they maybe just want a relative dir (relative to the cwd), but then surprisingly allow absolute paths to files otherwise?

Iirc we opted out of calling `./...` all the time because it is too slow and basically a waste while editing code.  And just taking the current file was not enough.  So we took: lint the folder (but *not* recursively) the current file is in.

**Comment by braver** [comment]
@kaste @cixtor just for me to have a clear picture here, this is an issue in the plugin, not in SublimeLinter core? Do you have enough info to attempt a fix/PR?

**Comment by cixtor** [comment]
I tested one more time using SublimeLinter 4.14.0 and golangci-lint 1.21.0 and the command _(which interestingly includes the project path rather than the file I’m inspecting)_ is running without problems and reporting warnings and errors on demand.

Something I noticed in the original report was this:

```
SublimeLinter: #6 linter.py:786
  WARNING: golangcilint output:
  level=error msg="[runner/typecheck] typechecking error:
  import \"/Users/my/code/path\": cannot inort absolute path"
```

Notice how it says “cannot **inort** absolute path”. The word **import** is misspelled.

@dpedu is this because you modified the console logs to explain something and mistakingly modified this text? Or is this the raw output of golangci-lint in your tests? The spelling mistake is not a problem in itself but it makes me think the developer(s) missed other small things in the version you have that could lead to real problems including the one you are experiencing.

Right now, I cannot say I can provide a fix with the information we have. Please share the content of `ipamdao.go` or create a minimal example that we can use to reproduce the error. I will gladly investigate and work on a fix as soon as possible.

**Comment by ivan-ahumada** [comment]
Hello. I'm having a similar issue to @dpedu. I've turned on SublimeLinter's debug mode and Sublime Text's console reads this on opening a go file named `exercises.go`. 
```
SublimeLinter: #1 linter.py:1699      Running ...

  /Users/ivanahumada/Documents/testPath  (working dir)
  $ /opt/homebrew/bin/golangci-lint run --fast --out-format tab /Users/ivanahumada/Documents/testPath

SublimeLinter: #1 linter.py:808       WARNING: golangcilint output:
level=error msg="[linters context] typechecking error: import \"/Users/ivanahumada/Documents/testPath\": cannot import absolute path"

SublimeLinter: #1 linter.py:810       Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #1 linter.py:1220      golangcilint: no output
SublimeLinter: sublime_linter.py:593  Linting 'exercises.go' took 0.11s
```
Contents of `exercise.go`:
```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, " + "world" // Purposely left syntax error to test linter
}
```
Let me know what other information I can provide in order to replicate this problem or help.

**Comment by cixtor** [comment]
@ivan-ahumada please answer the following questions:

- What version of Go are you using?
- What is the output of `go env` ?
- What other files do you have inside `/Users/ivanahumada/Documents/testPath` ?
- What is the output of `golangci-lint run /Users/ivanahumada/Documents/testPath` ?
- What is the output of `cd /Users/ivanahumada/Documents/testPath && golangci-lint run .` ?
- If you are not using Go Modules, try the following:
  * Execute `cd /Users/ivanahumada/Documents/testPath`
  * Execute `go mod init github.com/ivan-ahumada/testpath`
  * Execute `golangci-lint run .`
  * What is the output?

**Comment by cixtor** [comment]
@ivan-ahumada you are trying to inspect a Go file that is outside of your `GOPATH` (currently set to "/Users/ivanahumada/go"), and I believe this is one of the reasons (if not the only reason) for golangci-lint to fail. Notice that when you added the `go.mod` file via `go mod init` the linter started to print warnings as expected. I think you should reconsider turning `GO111MODULE` back on because that is how you are supposed to work in modern Go projects.

When I wrote _“If you are not using Go Modules […]”_ in my previous comment, it was because I managed to replicate the failure in my computer, but it was obvious that without `go.mod` the linter would not work.

You can either move `/Users/ivanahumada/Documents/testPath` to `/Users/ivanahumada/go/src/testPath` (without go.mod), or keep the folder where it is right now, but you must also keep `go.mod`, otherwise, tools like golangci-lint, among others, will get confused.

Please, let me know if that helps, or if you need more information.

**Comment by ivan-ahumada** [comment]
Ok so I have set `GO111MODULE="on"` and golangci-lint is now doing it's job inside the terminal as it should. However, it still isn't working inside Sublime Text and in the ST console I'm still getting the same error as before. I read the golangci-lint docs and although its laughable, I have no idea what I'm doing when I put this in the SublimeLinter preferences inside ST:
```json
{
	"linters": {
        "golangci-lint": {
            "env": { "PATH":"/opt/homebrew/bin/golangci-lint" }
        }
    },
    "paths": {
        "linux": [],
        "osx": [
            "/opt/homebrew/bin/golangci-lint"
        ],
        "windows": []
    },
    "debug": true
}
```
I've lost track of what I have tried so far as I've been at this for weeks now so in a desperate effort I have placed the path to the executable cause, again, I have no idea what I'm doing here. Thanks for all your help @cixtor

**Comment by cixtor** [comment]
I believe both paths you have in the JSON object must be of a directory instead of a file. So I think if you change your settings to this it might work:

```json
{
  "linters": {},
  "paths": {
    "linux": [],
    "osx": ["/opt/homebrew/bin"],
    "windows": []
  },
  "debug": true
}
```

I also think that you do not need to include additional entries in PATH if you are using the [SublimeLinter-golangcilint plugin](https://packagecontrol.io/packages/SublimeLinter-golangcilint) assuming that `paths.osx` is correctly set to the directory where you installed `golangci-lint`.

I created `~/Documents/testPath/exercises.go` and the linter works with the following configuration:

```json
{
    "debug": false,
    "linters": {},
    "paths": {}
}
```

Notice how I don’t have anything especial there. That is because my `PATH` environment variable already contains the folder where `golangci-lint` was installed. I set that via `~/.bashrc` (or `~/.profile` for many macOS users). I make sure to completely quit SublimeText after making these changes to make sure everything is loaded as expected next time I open it.

<img width="627" alt="golangcilint" src="https://user-images.githubusercontent.com/1933999/122321215-589eec00-ced8-11eb-8944-72492a006ca0.png">

**Comment by ivan-ahumada** [comment]
I have replaced my json with the settings you've provided and the problem persists even after quitting and reopening ST. Yes I have installed the SublimeLinter-golangcilinter plugin but I'm not sure that `paths.osx` is correctly set to where `golangci-lint` is installed. I have a `~/.zprofile` and the contents are:
```
eval $(/opt/homebrew/bin/brew shellenv)
eval "$(/opt/homebrew/bin/brew shellenv)"
path+=/opt/homebrew/bin
```
 In `/opt/homebrew/bin/` there is a `golangci-lint` executable file, presumably, except finder shows it as an 'Alias' file. 

`echo $PATH` returns: 
```
/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin
```
