### ISSUE TITLE
[FR] Support overriding `regex` in settings and defining ad hoc linters

### ISSUE THREAD

**Issue by ToxicFrog** [SublimeLinter/SublimeLinter#1719]
I'm trying to add a new linter. It basically just needs `cmd`, `selector`, and `regex`, and the regex is quite simple. But it looks like there's no way to do this except creating an entire linter plugin package and installing that.

It would be nice to be able to define ad hoc linters in the config file, by providing a `regex` setting.

**Comment by kaste** [comment]
Well, yeah... actually we have the whole class which defines the behavior of the linter plugin and also registers the plugin.  So although it looks completely declarative quite often just declaring the class has a runtime aspect (what's called meta class in python). (Aside: writing regexes for example in json is the ugliest thing anyone can do, just saying.)

You can of course have private linters, just in your Sublime User folder, it's not that you have to register against PackageControl and install. (Better to follow the convention though, and to put them in a directory and name the file `linter.py` because the hot-reloader will appreciate that.)

**Comment by braver** [comment]
Yeah, settings is not the way to define ad hoc linters. You can copy the [linter template (just the .py file)](https://github.com/SublimeLinter/SublimeLinter-template/blob/master/linter.py) into your User package directory and make up any kind of linter you like. Plenty linters are no more than what you describe, and setting up new linters via the template we have should be a breeze if you know some basics.
