### ISSUE TITLE
Commands to disable errors for a line or file

### ISSUE THREAD

**Issue by mauroreisvieira** [SublimeLinter/SublimeLinter#1739]
it was interesting, if the Sublimelinter, suggested options to cover an error or ignore it.

Something of this kind:

<img width="724" alt="Screenshot 2020-05-27 at 11 26 13" src="https://user-images.githubusercontent.com/3084774/83008663-6bb0f680-a00d-11ea-9ee2-cd8277d93de4.png">

**Comment by kaste** [comment]
Yes, I would like this feature as well. Usually there are some options here depending on the linter, like "disable for this line" or to add a comment at the preceding line "disable for next line", obv. different linters have different ways for spelling that. 

That being said I would like contribution from the community here.  I would suggest to make an add-on to SublimeLinter first (t.i. before we can consider integrating). (An add-on is just another plugin importing and using the code from SublimeLinter, for example listening to its events and just using its global error store.)  This is because a specific solution, say just for eslint, is much easier to get right than a generalized one.  

For the "show documentation" feature we actually had an UI already coded, but here we have a chicken-egg problem, nobody contributed or even gave a hint of how we actually could get documentation URLs given a linter name and a rule.  So the problem to solve here was and likely still is, first write a function in python `(linter_name, rule_name) -> url`.

**Comment by braver** [comment]
You’re getting into Language Service territory here, but maybe there is a generic way to provide something simple here. 

The options basically boil down to “comment before this line”, “comment after this line” and “comment at top of file”, and then having linter plugins provide templates for each. 

There are hardly any community contributors who will build new features, so we shouldn’t wait for that. If we want this we should try to get it off the ground for the plugins we use ourselves. This is something I’d use if we had it, so I would definitely like to have a go at it for pcs, eslint, flake8, stylelint and shellcheck.

**Comment by kaste** [comment]
The last year was very community driven. It was always these initial commits pointing me to all these refactorings I made.

Anyhow, for this feature I have clearly no UI/UX idea.  The coding is not the hard part here.

**Comment by braver** [comment]
> The last year was very community driven.

Ok, yeah, maybe my statement wasn't very fair. I guess my point is mostly that if we implement something in core we should go out and make use of it in as many plugins as we can (ie. those we use ourselves), and not wait for the community to pick up on it.

---

I like the idea of adding these commands:

1. ignore the error code(s) at my cursor position for this _file_
1. ignore the error code(s) at my cursor position for this _line_
1. ignore the error code(s) at my cursor position for this _line_ and onwards
1. disable the linter entirely for this _file_
1. disable the linter entirely for this _line_

A plugin should declare
- which of these it supports, 
- a template string for each
- if a line comment goes before the current line (e.g. eslint) or at the end (e.g. pep 8 `# noqa`)

The commands could be triggered via the command palette, or the context menu.

A problem with this, especially commands 5 and 6, could be that if you do this multiple times (especially ignoring multiple error codes for a file), you need to merge that with existing comments. So you also need a way to find and parse existing comments. I guess for line based comments you could get away with a more naive implementation that doesn't deal with this problem.

**Comment by kaste** [comment]
Just let us focus on 2.  You sit on an error and you fix it by ignoring.  Either you're  spot on the error marker, or maybe on that line; regardless, we can have multiple errors coming from multiple linters, we have `(linter_name, rule_name)` pairs, zero to n.

Afaik the command palette and the context menu is rather static, I cannot register or unregister entries.  Say I need to show "Ignore x from flake8 for this line" *and* "Ignore y from mypy for this line".  For the command palette we would need to register a separate (not a generalized) command for every linter *times* every action. Then some machinery to enable/disable them.) For the context menu, we need to add all possible combinations to a "json" file, then implement disable/enable (showing items) plus graying some items plus somehow make the description dynamic. This still wouldn't work if you have multiple errors coming from the same linter. 

Going to the command palette is not what I expect anyway because I interact rather directly with a squiggle, something I see.  So I expect mouse "hover", "right-click" context menus (not possible per above with the standard, default context menu? but we have `show_popup_menu` which looks ugly but otherwise *is* a dynamic context menu; but how do we open these then?). Other options? Phantoms just don't work because of text shifting all the time. A misused autocomplete which looks great at least?

**Comment by braver** [comment]
Via the command palette is usually easy to do in addition to the other options, and nice because it’s keyboard centric. Commands have a visibility that allows them to become available only if the context allows it.

That said this is indeed more tricky. We have n linters x m errors for each cursor position. So we need a way to resolve that. It’s messy to insert n commands into the palette.

Perhaps the best way to do this is via the tooltip. We could add a button for each error in the tooltip. This reduces it to 1 linter and 1 error. I agree we should only do no.2, you can always move that comment to the top of the file if you want that.

**Comment by mauroreisvieira** [comment]
We also can have a right click in error, like this for example:

<img width="724" alt="Screenshot 2020-05-28 at 16 50 15" src="https://user-images.githubusercontent.com/3084774/83163937-85cd0080-a103-11ea-881a-5f3a24e5de31.png">

**Comment by braver** [comment]
> We also can have a right click in error

Well, the trick with that is that a single point in the code can be covered by multiple errors from multiple linters. So then that context menu needs to be populated with options for all of them, or the command needs to do something very intelligent.

**Comment by braver** [comment]
Example and proposal:

<img width="571" alt="Screen Shot 2020-05-28 at 18 03 49" src="https://user-images.githubusercontent.com/2543659/83165329-a601bd00-a10d-11ea-8927-c173e16bf221.png">

Click the 🙈 for the flake8 error, then:

<img width="601" alt="Screen Shot 2020-05-28 at 18 05 18" src="https://user-images.githubusercontent.com/2543659/83165481-dba6a600-a10d-11ea-9ac3-25650a9836f9.png">

**Comment by braver** [comment]
(I also really want to be able to click the error code to copy it by the way)

**Comment by kaste** [comment]
What do you do with the error code in the clipboard?

For flake8 and mypy these annotations go always at the end of the line. For eslint I always use the disable-next-line convention. Is it okay to restrict this to one convention which also means one icon/action?

**Comment by kaste** [comment]
For accessibility we can add one command to the Palette which in turn shows a list panel/menu (GitSavvy style).

**Comment by braver** [comment]
> What do you do with the error code in the clipboard?

I paste it into `/* eslint-disable */` at the top of the file 😆 

> Is it okay to restrict this to one convention which also means one icon/action

One action per linter I would say.

> For accessibility we can add one command to the Palette which in turn shows a list panel/menu 

Sure, that's an option. I'd like to try and keep the interaction with the palette as simple as possible, but if we can make something work that'd be great.

**Comment by kaste** [comment]
This has been implemented in v4.16
