### ISSUE TITLE
How to selectively run SublimeLinter ("On background" mode) on particular files?

### ISSUE THREAD

**Issue by shmdhussain** [SublimeLinter/SublimeLinter#1772]
for example, the project is having the structure

````
.
├── a.js
├── b.js
└── lib
    ├── a_lib.js
    └── b_lib.js

````

I like to run the sublime linter on background for the a.js and b.js not on lib/a.js lib/b.js. 

Note: I know we can exclude the files but like to run only on selected files, here my exclusion list is more

Is it possible to do something like this?. Thanks in advance for any help

**Comment by kaste** [comment]
Do you want to change the *mode* per file, like these files should be linted on background, these other files only on save for example?

Otherwise, if you really want to exclude them I don't understand why 

```
    "excludes": ["*/node_modules/*", "*/dist/*", "*/lib/*"],  // etc.
```

should not do what you showed.

Or exclude everything in a sub folder:

```
    "${folder}/*[/]*",
```

**Comment by shmdhussain** [comment]
Thanks @kaste for the reply.

In our case,  linting enabled for the specific files (think 10 out 100 enabled), as remaining 90 files are legacy files, which we don't want to add  eslinting as of now.

rather than excluding all the 90 files, I thought if any option just to include those 10 files for which eslinting is required in sublime linter.

> Do you want to change the mode per file, like these files should be linted on background, these other files only on save for example?

My answer: that also will solve my problem, I could add `manual` linting for legacy files and `on save` for files which require linting

**Comment by braver** [comment]
Since you mention `.js` files, maybe you're using eslint. Some ideas:

- Maybe eslint has a configuration option in their config file that let's you do this, SL will respect that.
- eslint has a fixer that's really reliable. Throw all your legacy files through that fixer if all the errors get in the way. I have something similar set up for phpcs with a codebase with a lot of legacy. If I need to work on a file with a lot of errors, I first run a Sublime build system (CMD+B) that fixes most errors.
- Add a `eslint-disable` comment at the top of all the legacy files. You can probably do this quickly in a shell script, or just for the files you need to work on.

**Comment by kaste** [comment]
Closing because it already got stale.  Switching the mode from *manual* to * on_save* automatically is probably not an option here because in the end there is no simple filename matching rule to express what you want.  It sounds like these 90 files must be added manually to some ignore list, for example *.eslintignore*.
