### ISSUE TITLE
New place online to discuss Python editor/IDE integrations

### ISSUE THREAD

**Issue by brettcannon** [SublimeLinter/SublimeLinter#1777]
I just created https://discuss.python.org/c/editor-integration/27 as a place for those of us who support Python integrations in editors and IDEs to discuss things. Since this seems to be one of the  I wasn't sure how else to reach out beyond opening this issue. 😄

**Comment by kaste** [comment]
Thanks for lettings us know although ... this repo is rather unrelated to your group 😆

**Comment by brettcannon** [comment]
Since you provide things like flake8 and mypy integration with Sublime Text I think your project is exactly what I created the group for. 😄 Is there something I could rephrase somewhere to make it clearer that you and other extensions fit into that target demographic?

**Comment by braver** [comment]
SublimeLinter is a generic framework to integrate linter-like command line tools into SublimeText. We have wrappers for some Python tools, and it is written in Python (because the SublimeText API is). But Python isn’t a special target for us. We basically interface with stdin/stdout, so not a lot about what we do is Python-specific.

So, I can see a match, but we’re a bit more on the fringe than some other participants in the group. I don’t mind signing up and introducing ourselves though. If anything comes up that’s of interest or where we can provide insight, at least that would make us easier to find and reach out to.
