### ISSUE TITLE
Code formatting like `eslint --fix`?

### ISSUE THREAD

**Issue by katerlouis** [SublimeLinter/SublimeLinter#1780]
Visualizing and explaining the linting errors right in the editor is cool, but honestly the only thing I want is code formatting based on my eslint and stylelint rules. Basically just run `eslint --fix` on the currently open file. Preferably on save. 

But I cannot find anything related to that. I searched for `fix` `code formatting` `formatting` `format` and so on. Please don't tell me I have to switch to VSCode to get this functionality :'(

**Comment by kaste** [comment]
SublimeLinter does not ship any "formatting" functionality.  Over at the eslint plugin package I've tried a PR never finishing it, and I know that the "XO" plugin ships a solution because I reviewed it shortly. Not that I remember anything specific though.  

Maybe there are too simple solutions to the problem, like using the build system.  There is also not that much code share probably.  I mean, we run the linters here as getters, then process the information and present it to the user in various ways.  A code formatter is a blackbox sideeffect.  Sure, getting the right *executable* should be the same thing and could use the same user settings.  And generally the multi threading code, freezing the settings and the environment/context at any time.   

That being said, make it your project if you want.  I think, we're two very helpful people and good reviewers and feature designers.

**Comment by hapakaien** [comment]
You have to use [LSP-eslint](https://github.com/sublimelsp/LSP-eslint) to do that. It uses [vscode-eslint](https://github.com/microsoft/vscode-eslint) under the hood.

**Comment by braver** [comment]
There are two good solutions already: build systems, and LSP. I don't think SublimeLinter should add another solution to that mix, that feels like a waste of effort and code. Also because we have no existing feature that would make the interaction better that what those things already do (unlike the quick actions that neatly hook into our popups).
