### ISSUE TITLE
how do I customise colour for error types?

### ISSUE THREAD

**Issue by LollipopFt** [SublimeLinter/SublimeLinter#1839]
hi, i have this error message when hovering over the gutter:
![image](https://user-images.githubusercontent.com/62802897/147212222-2d69b5d5-9053-42fd-a74f-890d46c9eee1.png)
is it possible to make `1 help` and `1 note` a custom colour? i've tried `markup.help.sublime_linter` and others to no avail. thank you!

**Comment by kaste** [comment]
Oh, don't know that's a CSS thing.  We use `#sublimelinter-tooltip .help` etc for this.  @braver How is this customizable for end-users?

**Comment by braver** [comment]
You'd have to [extend, aka customize](https://www.sublimetext.com/docs/color_schemes.html#customization) the color scheme you use, and add stuff to the [CSS](https://www.sublimetext.com/docs/color_schemes.html#global_settings-css) for [popup_css]() so that you can tweak the [colors](https://www.sublimetext.com/docs/minihtml.html#colors) for the `#sublimelinter-tooltip`, [.error, .warning etc](https://github.com/SublimeLinter/SublimeLinter/blob/master/highlight_view.py#L864). I don't have any examples at hand but you should be able to work it out based on the documentation.

**Comment by kaste** [comment]
Closing as probably solved or orphaned.
