### ISSUE TITLE
Error after upgrading to babel 8 / eslint parser 7

### ISSUE THREAD

**Issue by imakeinterfaces** [SublimeLinter/SublimeLinter#1843]
I just updated one of my apps to use the babel 8 parser.
In the CLI running lint commands work just fine.

My eslintrc file looks something like this

```
  "extends": [
    "standard",
    "standard-react",
    "prettier",
    "plugin:jest/recommended"
  ],
  "plugins": ["react-hooks","prettier"],
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  }

```

In sublime i'm getting this error:
```
SublimeLinter: #1 eslint env.js ERROR:
======================================

JSON Decode error: We expected JSON from 'eslint', but instead got this:
SyntaxError: Cannot use import statement outside a module


Be aware that we only parse the last line of above output.
```

Edit: this must be a module problem somewhere but not sure where to look

**Comment by kaste** [comment]
I don't know enough about the latest eslint/babel stuff.  It should probably be reproducible on the command line/Terminal as we're not doing something _very_ special here and then you find knowledgeable people elsewhere, usually stackoverflow.

Turn on `debug` in the SublimeLinter settings and examine the log in Sublime's console.  Maybe we don't use the same versions of everything as on the Terminal.  Try closing Sublime and start it from the command line so that it inherits the ENV of the Terminal process.

**Comment by imakeinterfaces** [comment]
@kaste Appreciate the followup. After debugging as you suggested I found that my problem was that I was using eslint_d as my linter, and the tool which this uses, `Sublime​Linter-contrib-eslint_d` appears to be very much out of date. I guess eslint_d is not really usable in SublimeText in terms of available packages.

**Comment by kaste** [comment]
Iirc `Sublime​Linter-contrib-eslint_d` does not work anymore but the official `Sublime​Linter-eslint` does work with `eslint_d` **if** you set `executable` manually.

**Comment by kaste** [comment]
Closing as probably solved or orphaned.
