### ISSUE TITLE
Find `project_root` for python linters

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1883]
Two pull request (from the same person though) have been made to search a "project root" for python projects and set the working dir to it.  (We do this for node based linters but there the file `package.json` is basically mandatory so it is an easy play.)  

As always we look at `ale` which looks for these names, as usual going upwards the path starting with the filename.

```
  MANIFEST.in
  setup.cfg
  pytest.ini
  tox.ini
  .pyre_configuration.local
  mypy.ini
  .mypy.ini
  pycodestyle.cfg
  .flake8
  .flake8rc
  pylama.ini
  pylintrc
  .pylintrc
  pyrightconfig.json
  pyrightconfig.toml
  Pipfile
  Pipfile.lock
  poetry.lock
  pyproject.toml
  .tool-versions
```
https://github.com/dense-analysis/ale/blob/e4b20544082ba019d8095cbc24ffab43b15e8fc0/doc/ale-python.txt#L36-L55

Also from there just copy the possible venv names `ale` checks for reference:

```
.env
.venv
env
ve-py3
ve
virtualenv
venv
```
https://github.com/dense-analysis/ale/blob/e4b20544082ba019d8095cbc24ffab43b15e8fc0/autoload/ale/python.vim#L10

Note that ale also checks for the first directory **not** having a `__init__.py` file *iff* the above fails.  (So it may go upwards the path twice.)

https://github.com/SublimeLinter/SublimeLinter-pylint/pull/66
https://github.com/SublimeLinter/SublimeLinter-mypy/pull/53

We can of course also use the strategy to deploy only on a specific python linter for testing and then re-integrate into SL core.

**Comment by christopherpickering** [comment]
It looks good, but how about for cases where you are doing `mypy`, but also have a `.pylintrc` folder in subfolders w/ specific rules?

```
root
  .pylintrc
  mypy.ini
  >folder
      .pylintrc
      file.py
```

If you are running mypy and using the ale config, wouldn't it not find  the mypy.ini if there is a .pylintrc in the folder alongside the file you are linting?

It might be better to make a function where the implementer can pick what names of files/folders qualify as the project root?

Otherwise, this is great!
