### ISSUE TITLE
SublimeLinter hardlocks Sublime Text with deadlock on rapid line content deletes with annotations 

### ISSUE THREAD

**Issue by onlyhavecans** [SublimeLinter/SublimeLinter#1891]
This was originally submitted as sublimehq/sublime_text#5846

### Description of the bug

When using Neo​Vintageous (I did not test Vintageous), doing rapid ex commands with deletes on lines with annotations hard locks Sublime Text. I have been able to do this crash across multiple computers in safe mode

Please take a look at my reproduction steps for details. There is probably an even more minimal reproduction, but this is as far as I got since I didn't have a quick way of adding a lot of annotations otherwise.

Turning off annotation prevents the lockup for me; using ctrl+shift+k to delete lines does not lock up, and moving lines does not lock up. Doing a chain of ex commands with some deletes and annotation is currently my most faithful recreation.

This happens across multiple languages and files.

### Steps to reproduce

1. Start ST in safe mode
2. Install Package Control
3. Install `Neo​Vintageous`, `Sublimelinter`, `Sublime​Linter-contrib-yamllint`
4. Add the enclosed following `SublimeLinter.sublime-settings`
6. Open the enclosed `alacritty.yal` if yamllint is working almost every line should have a warning annotation. See screenshot enclosed
7. quickly type `<esc>jDjD`
8. Enjoy your pinwheel of doom

[Lockup replication files.zip](https://github.com/sublimehq/sublime_text/files/10514062/Lockup.replication.files.zip)

### Expected behavior

Sublime Text deletes to the end of the line and does not lock up

### Actual behavior

Sublime Text locks up and never recovers, requiring a force quit. ST is hanging waiting for the plugin to respond. The SublimeLinter is hanging [here](https://github.com/SublimeLinter/SublimeLinter/blob/0b540fa1aae0b925d1ab6c2856dcb1506b7f5883/highlight_view.py#L622). Looks like a deadlock.

### Sublime Text build number

4143

### Operating system & version

macos 13.1

### Additional information

This lockup happens both on my 1.4 GHz Quad-Core Intel Core i5 MacBook and my M1 Max MacStudio

### OpenGL context information

```plain
Intel
OpenGL Context Information:
  GL API Version: 4.1 INTEL-20.2.48
  GLSL Version: 4.10
  Vendor: Intel Inc.
  Renderer: Intel(R) Iris(TM) Plus Graphics 645

M1 Max
OpenGL Context Information:
  GL API Version: 4.1 Metal - 83
  GLSL Version: 4.10
  Vendor: Apple
  Renderer: Apple M1 Max
```

Stack trace from plugin host here
https://github.com/sublimehq/sublime_text/issues/5846#issuecomment-1409673359

**Comment by kaste** [comment]
Hi!  

- Do you know what `jD` actually does (under the hood)?  `ctrl+shift+k` actually does `ctrl+l; <backspace>`  What *could* be the difference here?
- When https://github.com/SublimeLinter/SublimeLinter/blob/0b540fa1aae0b925d1ab6c2856dcb1506b7f5883/highlight_view.py#L620-L622 locks, who's calling that, t.i. who *holds* the lock?  The traceback you show has https://github.com/SublimeLinter/SublimeLinter/blob/ddab676bc003f3d9e2852dd3298c66b95a0065ac/highlight_view.py#L647-L650 at its edge, and `on_modified` as the initiator.  For sure, `on_modified` does run when we delete a line.  (Then we basically lookup which regions/squiggles are outdated and, before removing them in a later step, redraw them "invisible".)  

I'll try your zip in a moment.

**Comment by kaste** [comment]
Hard to replicate.  I probably suck at typing `jD` fast enough?

**Comment by kaste** [comment]
Can replicate with just `ctrl+shift+k`.  👍 Thanks for reporting!

**Comment by kaste** [comment]
Not trivial to fix.  The stack trace pointing to `erase_view_region` mislead me.  Actually it just happens, races, when we edit the buffer (e.g. delete lines that have squiggles) and somehow at the same time we want to draw new results coming from the linter.  

The lock that deadlocks here is actually here to prevent or orchestrate that exact case because editing updates happen (or are processed) on the UI thread, and linter results fly in async on a different ("worker") thread.  Instead of serializing the side-effects manually, the idea was that an ordinary `lock` would do that for us rather elegant, and we just assure that we don't call us recursively, t.i. we have simple side-effects.  The lock groups

```
	view.[add|erase]_regions(key)
    in-memory-store.update(key
```

operations.  This looks innocuous and would work *but* the views itself have an internal lock.  That is:  a task on the UI thread locks the view, and calling out to the view from a different thread first waits or wants to acquire that same lock, thus we deadlock.  T.i. we deadlock because the call `view.add_regions()` called from the worker thread never returns *if* the UI thread is busy.

**Comment by onlyhavecans** [comment]
Thanks for looking into this, I updated the title. I am such a long-term vim user I naturally take to vim keystrokes over sublime texts and I am very fast at them for it

> Do you know what jD actually does (under the hood)
I haven't dug into the source code of NeoVintagious but `j` moves down one, and `D` deletes all text to the end of the line, how it does this in ST on a technical level is unknown to me, but if `ctrl+shift+k` also causes the hard lock that simplifies the replication!

I updated the title in light of that

**Comment by kaste** [comment]
Let's :ship: 4.20.3 with a 🙏  
Thanks for the report again.
