### ISSUE TITLE
Set color for errors of type "suggestion"

### ISSUE THREAD

**Issue by loughnane** [SublimeLinter/SublimeLinter#1898]
I'm not sure if this can be done, but I've been poking around with a few incantations of the recommended [linter settings](http://www.sublimelinter.com/en/stable/linter_settings.html) and I can't get it to work.

I'm using [Vale](https://github.com/errata-ai/vale) as as a linter for prose and the levels are `warning`, `error`, and `suggestion`. The first two play nice with sublime linter, but I don't see `suggestions` highlighted, though they do show up in the console as I'd expect.

Here's the latest version of the style I've got in `SublimeLinter.sublime-settings`. 

                {
                    "scope": "region.bluish markup.info.sublime_linter",
                    "mark_style":"outline",
                    "types": ["suggestion"]
                }

Any thoughts on how I can get this to work?

**Comment by kaste** [comment]
From a short look at the adapter code it looks like it doesn't catch suggestions at all.  See the regex at https://github.com/SublimeLinter/SublimeLinter-vale/blob/0cd7c5a1841af358ae6d0ce4df934fffb4b0d74b/linter.py#L23

If that's the case the adapter code itself needs a PR.  Either a changed regex or maybe json is available too.

**Comment by eread** [comment]
@loughnane @kaste I've raised a PR to add support for `suggestion`: https://github.com/SublimeLinter/SublimeLinter-vale/pull/11.

I came across this issue because I was looking for information on the colors used by Sublimelinter. In my PR, errors come up as red and warnings come up as yellow as they always did, but suggestions are also coming up as red.

In Vale CLI itself, suggestions are treated as blue. That's also true of: https://github.com/errata-ai/LSP-vale-ls. I think the colors for these things come from the Sublime Text theme?

**Comment by kaste** [comment]
By default all new or unknown error types are styled as "errors".  You can change that just as @loughnane pointed out.  More details are here: https://www.sublimelinter.com/en/latest/linter_settings.html#styles

You add these style rules in the (global) SublimeLinter settings.  

As @eread implemented the fix (just shipping now) I close this one.
