### ISSUE TITLE
lint_mode options to for specific linters

### ISSUE THREAD

**Issue by caesarsol** [SublimeLinter/SublimeLinter#244]
Hello, I explain with this scenario:

I'd like to lint by default (in `lint_mode: background`) Ruby files with SublimeLinter-ruby, and lint only by request with the more strict SublimeLinter-rubocop (that performs also lots of style checks on Ruby files).

The linting option `lint_mode: manual` could be used to lint only by request, but it can only be applied globally. Is there a way to apply that option only to one specific linter?

(I find strange that noone made this question before, but I couldn't find any trace on GitHub nor online... Sorry if I'm making a duplicate)

**Comment by ptim** [comment]
+1 ! would love to be able to set linting mode via [Linting Settings](http://www.sublimelinter.com/en/latest/linter_settings.html).. 

I've tried to add 

```
    "lint_mode": "save only"
```

to specific syntaxes, but only the global value is honoured..

**Comment by dmnc** [comment]
Similarly I would love to be able to set "show_errors_on_save" on a per syntax basis.

I was hoping I could do this through the Syntax Specific .sublime-settings file but am failing miserably.

As an example use case, I really want to be warned aggressively when an XML file is invalid, but I don't really mind if a .scss doesn't have the recommended style.

**Comment by reagle** [comment]
I have the same exact question, I'm surprised there's no response. I want my python aggressively linted, but my prose only on manual.

**Comment by braver** [comment]
This isn't compatible with our current architecture. We may want to offer this some day, so I'm keeping it open, but it's really "won't fix" for the foreseeable future.

**Comment by kaste** [comment]
This is, how I see it, an important UX issue. But it is not about the `lint_mode`, we have the lint mode as a relict for slow CPUs and save battery mode on laptops.

This here is a general UI/UX problem. We have often very strict rule sets even as a pre-commit or pre-ship requirement. But this generally distracts from solving the problem. Styling is not problem solving. So, while writing code, actually all the shitty whitespace noise, is irrelevant. But 'non-declared-vars' and syntax errors are of great importance. I probably don't even have to try to hit save with those. It won't compile or run anyway. 

So @braver, I think we should have a broader issue on this one. And we should tackle it. This one could then be closed bc it already suggests a solution.

**Comment by braver** [comment]
> But 'non-declared-vars' and syntax errors are of great importance. I probably don't even have to try to hit save with those. It won't compile or run anyway.

Sure, but that's why now in SL4 you can style the stylistic errors to be very subtle, and filter them out of the output panel. That's how I envision you set those to "I'll deal with that later". Lint mode isn't how you deal with that. It's always a good idea to hit save a lot, you shouldn't become hesitant about saving because it will show you all those white-space errors you're not interested in right now. Also, a linter may give both important (unused vars) and unimportant (trailing whitespace) feedback. SL4 allows you to style based on error codes, you cannot (or should not) run a linter one way in the background and another on save.

Lint modes other than "background" are for linters that need a file on disk and can't deal with temp files, or for when you want to save cpu cycles. Saving or not is not a work flow decision, you should always save a lot continually. We shouldn't try to repurpose that feature for something else just because it's there. I think SL4 already solves the use case here.

**Comment by kaste** [comment]
@braver You sure read 
> But it is not about the lint_mode, we have the lint mode as a relict for slow CPUs and save battery mode on laptops.

and 

>This one could then be closed bc it already suggests a solution.

**Comment by braver** [comment]
Probably read but not fully processed it. Struggling to keep up with you today man!

> And we should tackle it.

I think we already tackled it then?

**Comment by kaste** [comment]
Implementing the feature request here present is fairly easy.  When we hit the queue (in front of the backend) we pass it the reason `background|saved`, which will pass it further down to `backend.lint_view`. This is only one step passing, not deep down. `lint_view` already is responsible to filter which `linters` actually should run. It uses the settings. We check for `excludes` and `disabled`. So this is relatively easy to implement, but has it low or high impact for the user?

> I think we already tackled it then?

I don't think so. *while writing* means that we de-highlight or de-emphasize some regions while editing.

E.g. you have this

![image](https://user-images.githubusercontent.com/8558/35094902-07a12078-fc47-11e7-94e1-6cdc9f9ec61a.png)

If you fix this error or line, the highlight could go away immediately. (And then reappear if you still have an error after your edit, of course)

**Comment by braver** [comment]
In that case lint mode is the wrong thing to be thinking about. What you're saying is that for some linters or error codes, you want to change the styling when the buffer is dirty. So you can de-emphasize it when editing, and have it pop out when you hit save. 

I think that would be a nice addition. But I also think it requires effort from users to set up and only a hand full of users will end up using this. It also requires linter plugins that properly expose their error codes and not many do that (and we don't have a serious interface for it anyway), because this feature doesn't make sense on a per linter basis.

**Comment by braver** [comment]
Ok, lots of ideas on what use cases this could cover or fancy other modes we can dream up. However, let’s keep it focused. This is the meat of feature request:

> I'd like to lint by default (in lint_mode: background) Ruby files with SublimeLinter-ruby, and lint only by request with the more strict SublimeLinter-rubocop (that performs also lots of style checks on Ruby files).

If someone has other request or ideas, please open a new issue about it.

**Comment by braver** [comment]
The base level linter feedback is in the view, with highlighting or the gutter. Both can be disabled separately per linter, but they’ll always be listed in the popups because why run a linter otherwise. 

The panel provides an additional overview of errors that you can use as a checklist. You can also use it to navigate, so you can use it to run through all errors, e.g. before committing. The filtering allows you to leave TODO comments out of this checklist, or have a list of just the todo’s.

So there are several visualizations and they all have their own toggles, hopefully in a way that allows you to build your own work flow.

One thing you cannot do right now is have one linter on demand (we already have a “manual” mode, but again only globally for all linters) while running the others continuously. I like the idea of running pydocstyle manually for instance. I can remove it from the panel, or only turn on the highlighting when I’m interested in it, but it would still be running all the time wether I’m interested in it or not.

**Comment by kaste** [comment]
Closed via #1416
