### ISSUE TITLE
Path lookup failure due to slow shell startup

### ISSUE THREAD

**Issue by RR2DO2** [SublimeLinter/SublimeLinter#57]
On my slightly older machine, and due to the inclusion of a few scripts (mainly related to virtual envs) in .bashrc, my bash doesn't always start up that fast. However, the following code is in lint/utils.py:

```
    try:
        out, err = proc.communicate(timeout=1)
    except subprocess.TimeoutExpired:
        proc.kill()
        out = b''
```

causing a PATH failure lookup with the following error:

SublimeLinter: Could not parse shell PATH output:
<empty>

**Comment by Ulysses-Odysseus** [comment]
Just to touch the importance of .bash_profile once again and this might help some else. 

So I had my npm-packages installed in a different location instead of default settings, and I was referencing the path from my .bashrc with no luck, for the path to be read by sublimeLinter.
Until I changed the code to .bash_profile and all felt right in place. 

# NPM Reference Directory
NPM_PACKAGES="${HOME}/path-to-packages-dir"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
PATH=$NPM_PACKAGES/bin:$PATH

Just in case this might help.
thank you @aparajita

**Comment by jawshooah** [comment]
@Ulysses-Odysseus You could accomplish the same thing by sourcing `~/.bashrc` from `~/.bash_profile`:

```bash
[ -s ~/.bashrc ] && source ~/.bashrc
```

**Comment by Ulysses-Odysseus** [comment]
@jawshooah: .bash_profile was sourcing .bashrc the whole time but sublimelinter didn't recognize that, so until I put the path script in .bash_profile it worked. 

Like aparajita mentioned 

You still don't want stuff relating to interactive shells running in a non-interactive shell. So:
On Mac OS X, PATH stuff should be in .profile/.bash_profile, and source .bashrc in .profile/.bash_profile if it's an interactive shell

**Comment by jawshooah** [comment]
Ah, good call. That's what I get for not checking the comment history.
