### ISSUE TITLE
On Posix: Setting @python to a virtual environment still uses a system linter binary

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#656]
If you point `@python` to a virtual environment, SublimeLinter will still ask e.g. `which(flake8)` 

https://github.com/SublimeLinter/SublimeLinter3/blob/d95681c9f50f86880c6913a788b9f0be85a92de7/lint/util.py#L950-L957 

which will return the globally installed flake8 if any. As reported https://github.com/SublimeLinter/SublimeLinter-flake8/pull/51#issuecomment-339977973 That's not the purpose of having everything in a virtual environment. 

Suggestion: If the user points to virtual environment, we can find a suitable installed binary just by looking at `<venv>/bin/<linter>`. This is BTW what you actually do on Windows. 

[Aside: right now `@python` must be set to a python binary, instead we should set it to a base dir of a python environment. From there we can find the installed binaries quite easily. See #654]

**Comment by FichteFoll** [comment]
I kind of touched on this in my comment in #653, although I wasn't aware that `@python` already takes the path to a Python executable.

I agree that in order to have proper virtualenv wrapping, the path to the env itself should be specified and executables within that env need to be determined based on the usual paths used within that, i.e. `bin/` on UNIX and `Scripts\` on Windows. 

Also, technically the virtualenv needs to be *activated* before executables within it are run, since a lot of environment other than just `PATH` are changed as well.

**Comment by kaste** [comment]
Done.
