### ISSUE TITLE
[beta] start up time regression?

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#735]
If I startup Sublime, using beta, it feels slower and actually a bit laggy, t.i if I click around I feel that the computer is doing work. Also, on my laptop the fan spins for a short time which actually never happens otherwise except when I'm benchmarking. Did you change something here, or did *I* change something completely unrelated to this plugin?

Do you lint all open files, whereas before maybe only the visible view were linted immediately? It really takes too much time to see the errors on the active view.

**Comment by pykong** [comment]
Unless you have opted for the manual lint mode, all open views are linted on startup indeed.
Not sure if this is the (only) reason for any startup delay.

**Comment by kaste** [comment]
And this is a new feature?  [Startup takes roughly 15secs on my laptop btw]

**Comment by braver** [comment]
I think this may be new behavior because before the output panel SL would only concern itself with the current view. I noticed some latency too, but I’m also running about 6 linters now which I would never have done before. Perhaps we should lint only when a view receives focus, but then they won’t show up in the output panel until they do. I think that may be a good trade off though, we shouldn’t hit the cpu’s that hard on start up.

**Comment by pykong** [comment]
This one of the rare occasions where I like to add a new option to the settings.
We should neither allow the panel to remain empty which is an inconsistent.
But also we should consider user's with slower setups or running multiple linters in parallel.

**Comment by braver** [comment]
I’m not sure a setting will do though. One day I might open a project where I’ve got a hundred files open and then I don’t want SL to try to lint them all. But usually my machine is fast enough. Perhaps a lazy approach would be better. The panel would show files that have been linted, so it’s easy enough to understand that files only show up there after they’ve been viewed. Perhaps we can introduce a lint-all-files command or lint all files only when the panel is toggled.

**Comment by pykong** [comment]
I opt for a minimal approach here. Neither do I want to discriminate against slower system's, nor do I want to introduce much more complexity into SublimeLinter. Especially since we do not know whether the issue at hand affects many user's or how severe it is at all. (Note: Startup is running fine for me and @braver after all.)

> The panel would show files that have been linted, so it’s easy enough to understand that files only show up there after they’ve been viewed.

The consequence would be that the user is required to click each view individually to make it listed in the panel. Especially when there are many views, this is not only a major UX inconsistency but also becomes a real hindrance to using the panel for navigation.

> Perhaps we can introduce a lint-all-files command or lint all files only when the panel is toggled.

That would be much more complex than simply introducing one new setting.

Let me add the setting `lint_all_views_on_startup`. It will be explained in the accompanying comment, that when turned to `false` it will be the user's responsibility to focus views to get them linted.
This is the cleanest and most straightforward solution, IMHO.

**Comment by braver** [comment]
Having a fixed setting for a problem that's situational doesn't seem like the right approach to me. Some times I might wish it to be true, some times I'm good with it being false. If I always have performance issues I might simply opt to run linting only on save. 

Performance is always super important, so there needs to be a solid approach that works without a setting. Perhaps we should just be more lazy about looping through all the views that need linting. To be clear, I'm against having a setting here and feel like it just indicates we don't understand the problem well enough to design a solution for it.

**Comment by pykong** [comment]
The panel should always reflect the set of open views.
Anything else breaks consistency. And is bad UX.

I am not necessarily in favour of introducing a setting, rather than totally against crippling the panel with errant behaviour.

> If I always have performance issues I might simply opt to run linting only on save.

In which case no lint on startup for all views is triggered, as of the current build.

> Performance is always super important, so there needs to be a solid approach that works without a setting. [...]  we don't understand the problem well enough to design a solution for it.

There is not much too understand about linting requiring computing time. And that time requirement rising with total file size.

A possible to solution to this problem could be to persist errors across sessions.

See issue where I suggest cleaning up the internal data structure.
https://github.com/SublimeLinter/SublimeLinter3/issues/734

**Comment by FichteFoll** [comment]
I'm with @braver on this. A command to lint all open views sounds like the general and more approachable solution, which can also be useful in other situations.

I also agree that the panel not indicating that not all views have been linted is inconsistent and should be addressed in a way. Ideally it would just mention which views haven't been linted at the bottom. I think it's possible to do this with the current `can_lint` architecture without actually running the linters.

**Comment by pykong** [comment]
As long as the panel accounts for all lintable files any solution is totally ok to me.
Those files must be listed in one way or the other, so the user knows he either needs to focus views of interest or run the new `lint_all` command.

**Comment by braver** [comment]
These suggestions sound like a good direction to me 👍🏻

**Comment by kaste** [comment]
Hm, sorry still confused. I don't see an actionable resolution here.

As a user, I want to see linter errors on the visible views as fast as possible. If it burns my CPU or not is a different q. Implemented as #745 

Since Sublime does not open the linter panel on startup, this panel cannot be inconsistent to anything. Ideally we startup lazy, and lint the other files as soon as the panel opens. Or in the background, if you will. But then e.g. our 'views' are still not lazy e.g. `sublime_linter.highlight` is totally inefficient bc it draws regions and marks on invisible views. The same goes for the proposed Indicator implementation which runs even if there is no view attached to this Indicator. The indicator in #744 is more efficient here. 

If we queue multiple or a lot of files, parallel/async execution is the only way. Note also that the usual linters can run multiple files or a complete directory structure very, very efficient. So I propose that we run `flake .` here. This would really be an order of magnitude faster.

**Comment by braver** [comment]
Honestly I haven't taken time yet to form a solid opinion myself. 

My hunch right now is that the panel really isn't consistent to anything anyway and it's not a problem if all open views aren't linted. Haven't tested that assumption yet though. 

I *am* pretty sure that on startup we shouldn't lint anything you can't see. So we need a solution that introduces a certain laziness, but how lazy and when all views should be linted (or if that needs to happen at all) I'm not sure yet. 

I'm now also pretty sure settings or commands that users have to call should be part of the solution.

@pykong has proposed some changes, I'm testing those. Your proposals are also very welcome and I'll have a look at those as well. 

> If we queue multiple or a lot of files, parallel/async execution is the only way

My current thinking is that we may never have to do that, but if it happens I agree it should be parallel/async.

We're talking about views here, which may not be in the same folder, may be in any kind of language, and may not reflect a file on disk. I don't think using the batch/project/folder features of the linter programs is a good match for us.

**Comment by braver** [comment]
I think #745 covers this well enough for now.

**Comment by kaste** [comment]
Ah well, most of the times, you have set up a project and a `flake8 .` or `eslint` would be what you want. 

As soon as you have type checkers as linters, this is a very relevant feature, bc if change a type you actually want to know if you broke the whole system or not. If you look at VSCode here, they don't do it for TypeScript and this is really annoying. They tell you 'no problems found' and then later you discover that your CI doesn't build your code anymore.

**Comment by braver** [comment]
Ok, sure, but that’s outside our scope. LSP can also run linters as part of the language services, and in general such solutions are project-aware. If you want more features and type-checking, I think LSP is where you should go looking.
