### ISSUE TITLE
[beta] Enable configuring specific executable for NodeLinter

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#781]
I think we now have this ability for the PythonLinter, does that also work for the node based linters? Would solve https://github.com/SublimeLinter/SublimeLinter-eslint/issues/147 and similar use cases.

**Comment by kaste** [comment]
This is at least trivial to add.

**Comment by FichteFoll** [comment]
Should consider adding this to other specific linter implementations as well, if they don't have it already.

**Comment by kaste** [comment]
I think I would like to go for a 'core' setting `executable` in `Linter`. We would check for it in `context_sensitive_executable_path` which is part of our public API and wildly used. The users (plugin authors) would have to opt-in then, iff they already overwrite `context_sensitive_executable_path`. Otherwise everyone gets it for free, and the main subclasses of `Linter` are under control. 

This is a potential break, of course, bc plugin authors may have chosen the name `executable` for their own sake. It is likely that even in that case, our implementation would be just a no-op, bc 🎱 the name `executable` just suggests a specific usage here.
