### ISSUE TITLE
Cannot find the gutter theme

### ISSUE THREAD

**Issue by ilyeah** [SublimeLinter/SublimeLinter#8]
After installing a latest version error message will pop up
SublimeLinter: cannot find the gutter theme "Default", and the default is also not available. No gutter marks will display.

And I can't switch the gutter theme with the command+shift+P menu

When i change gutter theme to Blackberry with the User Settings
pop up message shows again.

**Comment by ics-brettma** [comment]
Issue remains - 30/09/15

**Comment by grotewold** [comment]
@ics-brettma,

Aparajita is not an active contributor to SublimeLinter anymore. While it's [strongly discouraged](https://packagecontrol.io/packages/SublimeLinter-jsdebugmarkers) to install SublimeLinter from its source, what version of SL are you using? What does your console say? To be honest, I've never been able to replicate this, so it's going to be tough for me to help until you find out what is wrong.

**Comment by ics-brettma** [comment]
@grotewold My installation steps were merely to clone this project directly into ~/.config/sublime-text-3/Packages/SublimeLinter3 so I figuire my version is 5951b647e96370d36727eb6fcee6de5ae6b9a156

**Comment by ics-brettma** [comment]
@grotewold Here's the console output:

`DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /home/dev/.config/sublime-text-3/Packages
packages path: /home/dev/.config/sublime-text-3/Packages
state path: /home/dev/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/dev/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.503772
startup time: 0.79482
first paint time: 0.853496
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin JDebug.JDebug
reloading plugin JDebug.log
reloading plugin JDebug.settings
reloading plugin JDebug.util
reloading plugin Javatar.Javatar
reloading plugin SublimeLinter-javac.linter
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/dev/.config/sublime-text-3/Packages/SublimeLinter-javac/linter.py", line 13, in <module>
    from SublimeLinter.lint import Linter, util
ImportError: No module named 'SublimeLinter'
reloading plugin SublimeLinter3.commands
reloading plugin SublimeLinter3.sublimelinter
plugins loaded
[Javatar] v2.0.0-prebeta.3
error: SublimeLinter: cannot find the gutter theme "Default", and the default is also not available. No gutter marks will display.
SublimeLinter: debug mode: off 
[Javatar] Snippet Class.javatar-snippet loaded
[Javatar] Snippet Enumerator.javatar-snippet loaded
[Javatar] Snippet Interface.javatar-snippet loaded
Package Control: Installing 1 missing dependency
[Javatar] No JDK found
error: Javatar cannot find JDK installed on your computer.

Please install or settings the location of installed JDK.
Traceback (most recent call last):
  File "/home/dev/.config/sublime-text-3/Packages/Javatar/utils/constant.py", line 202, in check_startup
    Constant.post_startup()
  File "/home/dev/.config/sublime-text-3/Packages/Javatar/utils/constant.py", line 93, in post_startup
    StatusManager().show_status("Javatar is ready")
  File "/home/dev/.config/sublime-text-3/Packages/Javatar/utils/constant.py", line 172, in check_conflicts
    from ..extensions.linter import JavatarLinter
  File "/home/dev/.config/sublime-text-3/Packages/Javatar/extensions/linter.py", line 11, in <module>
    from SublimeLinter.lint import Linter, util
ImportError: No module named 'SublimeLinter'
Package Control: Installed missing dependency bz2
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
Package Control: No updated packages`

**Comment by grotewold** [comment]
This output is saying that SublimeText can't find SublimeLinter. Also you should restart your ST for package controls sake.

**Comment by DavidPesta** [comment]
I also have the same problem as @os-brettma, exactly as he described.

**Comment by 0492wzl** [comment]
issue remains,

**Comment by alvarolm** [comment]
@groteworld and for those who doesn't use package control or directly want to edit the py code ?

**Comment by groteworld** [comment]
@alvarolm Put your repo in the SublimeText/Packages directory, and restart ST.

@0492wzl what does your console output say
