### ISSUE TITLE
Redundancy in GoTo commands

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#801]
The merger of #797 introduces the update of the panel's selection based upon caret position in the view. 
This IMHO solves #681 #715 #755 

Now I see a potential overlap of function with the newly implemented "old style" GoTo @kaste implemented.

For example have we even considered to continue using <kbd>F4</kbd> / <kbd>shift</kbd> + <kbd>F4</kbd>, instead of introducing two new commands? We could maybe use an on_command listener and intercept "next_result" and "prev_result". If our panel is the active we can execute additional logic, if required for advanced behavior added in #788 (like not jumping to next file).

After all the work we did to cleanup and rip out redundancies, this duplication feels like a regression to me. Right now we end up with two different **GoTos**. I am sure I am not the only one seeing some redundancy here. What can we do to make this harmonious?

**Comment by FichteFoll** [comment]
>We could maybe use an on_command listener and intercept "next_result" and "prev_result". If our panel is the active we can execute additional logic, if required for advanced behavior added in #788 (like not jumping to next file).

I thought about this too, but there is a small issue with it: The two command sets differ in functionality. F4 explicitly goes to any error to any file it encounters, while the custom command explicitly does not leave the current file. Imho these are pretty exclusive operation modes.

Maybe @gerardroche has an idea about this, too?

**Comment by braver** [comment]
I wouldn’t see it as redundancy. Both offer similar but different features that overlap. However, “F4” utilizes existing functionality in Sublime Text and conforms to existing patterns. I find that very useful. 

We could make our own goto functionality have the ability to jump between files and thereby remove the need to use “F4” at all to navigate errors.

> For example have we even considered to continue using F4 / shift + F4, instead of introducing two new commands?

Yes of course but that’s impossible. What F4 does is contextual by design. We cannot listen to it and react to it, because we cannot know the context in which it operates. The reason I requested the new commands at all is because we need a command that jumps to errors regardless of what panel you used last. We cannot enhance what F4 does because we cannot rely on it being tied to SL.

Do remember that we didn’t provide the F4 command, it’s just there because we present errors correctly an ST picks that up. 

I think enhancing our own goto command to fully cover all use cases would simplify things for users.

**Comment by kaste** [comment]
First Proposal (I mean I use this like 40minutes):

- If the panel is open, I expect to jump to the next error in whatever view. Just the next result from the list I see.
- If the panel is hidden, I want to stay in my active view. Bc everything else confuses me.
- I expect that 'Soft-Undo', 'Jump back' works. (It doesn't currently.)
- I still expect a smart order of the views here.  See #791 now #681

**Comment by gerardroche** [comment]
Goto result is not necessarily the same thing as goto error. In the context of Sublime, *results* imply a build result attached to an output panel, and goto result is bound to it. A side-effect of that is if you run another build system, e.g. a test suite, goto result is now bound to the test suite results, whereas goto error is not. I don't see any possible way to work around that, and even it is possible, it probably isn't worth working around.

kaste mentioned there's a context different between the diagnostics panel being show vs hidden, and that if it's not shown then the goto result is bound only to the active view. That sounds about right to me. If possible give the option of both functionalities  i.e. you to have it a) if the panel is open then goto result uses its results, if it's not open then goto result only uses the active results, or b) goto result always uses the panels results.

**Comment by braver** [comment]
I think it might not be such a bad idea to run the "next_result" command when the panel is open, and our "goto error (next)" when it's closed. Not sure if you can hook this up in the keybindings, I never did anything with the context checks you can do here.

**Comment by braver** [comment]
We're basically saying "use goto", which we have full control of and takes a bunch of args, whereas people can use next/prev_result to interact with the contents of the output panel if they want to. But if they do, it'll basically have the same limitations it has for every other application of the ST output panel.
