### ISSUE TITLE
Actually where is the `${project}`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#824]
I wanted to refactor the settings-tokens-stuff after #581 esp. https://github.com/SublimeLinter/SublimeLinter/pull/581#issuecomment-357340886

Also related #750 and #818 

So, how the find the project home?

1. If you just open a file in a new window:

> >>> w = sublime.active_window()
>>> w.project_file_name()  # None
>>> w.project_data()  # None

`w.extract_variables` also doesn't contain anything useful. That is okay.

2. If you open or drag a folder into Sublime without a project file:

> >>> w = sublime.active_window()
>>> w.project_data()
{'folders': [{'path': 'C:\\Dev\\Sublime Text 3'}]}
>>> w.project_file_name()  # still None

`w.extract_variables()` will not contain that folder.

3. If you open a folder with a project file:

`w.project_data()` will have all the settings, the first folder in folders has whatever the user typed here, but most probably `'.'`, which we cannot resolve via `os.path.realpath`, but `extract_variables` will have expanded path at ~~`['project_path']`~~ EDIT: it's `['folder']`

Any additional folder is always a realpath.

Any comments here @FichteFoll @braver @pykong, otherwise I'll go from here

**Comment by FichteFoll** [comment]
I think the fundamental idea was to find the project folder that the currently active file belongs to, if any. Sometimes you might want the path where the project file is (in extract_variables) and sometimes you store the project file at a different location or have multiple folders on your project and want to use the project folder the file is in. We can't make that decision for the user, but we should provide the means to make that decision. Imho we should inherit the variable names from st internals as they are used in build systems and then add our own variables on top of that. 

The window object has a folders method, which iirc resolves relative paths, so that can be used as a baseline.

**Comment by kaste** [comment]
I will look into `folders()` which is a getter not a method.

**Comment by kaste** [comment]
`folders()` is 👑. Ty, @FichteFoll
