### ISSUE TITLE
Update plugin readme’s about ${project}

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#848]

**Comment by shulard** [comment]
I ran a search across the whole organization: https://github.com/search?utf8=%E2%9C%93&q=org%3ASublimeLinter+project&type=Code

This give me 38 results, is there a way to ping all the linter maintainer ? Since the `${project}` removal is part of the SL4 release which is not finalized ATM, do we need to maintain the 2 versions in the docs ?

If someone use ${folder} instead of ${project} on SL3, it will not works...

**Comment by braver** [comment]
Well if they’re in the org I can just go a push a change on all of them. We should remove such examples from readme’s and direct users to the centralized docs so we have a chance of maintaining them. 

Non-org plugins should do the same, but if it’s more than a handful I don’t feel like opening issues everywhere. They’ll either get with the program eventually, or not.
