### ISSUE TITLE
Log SL version if debug mode is enabled

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#855]
When the user enables debug mode, SL's version should be logged for better debuggability.
I suggest basing this on a `package-metadata.json` file, if available, or the git revision, if `.git` is available. I don't exactly recommend hard-coding a version string in the code somewhere, but that *could* be used as well.

**Comment by braver** [comment]
Reporting the version from `package-metadata.json` is a good idea. 

Git revisions don't tell you anything about the local state of the code. If someone is reporting issues based on a personal clone of this repo, he/she should provide any details necessary to make a fix including the version the issue was found on. That the package metadata couldn't be found is all the info we need at that point.

Hardcoding is also not an option, we don't have systems in place to update such a value on release.

**Comment by kaste** [comment]
It would probably good if plugin authors could read a version as well. Makes it easier to write SL3/SL4 code.

**Comment by braver** [comment]
fixed in 83adac2d728c9b81e7ced942813414b845dcf406
