### ISSUE TITLE
quick settings.Settings code review

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#862]
observer is always None

https://github.com/SublimeLinter/SublimeLinter/blob/8b46320aca3d61bc76f88b315e1f1cab78c548f1/lint/settings.py#L101-L105

bc this is the only caller:

https://github.com/SublimeLinter/SublimeLinter/blob/8b46320aca3d61bc76f88b315e1f1cab78c548f1/lint/settings.py#L64

--- 

This is never called

https://github.com/SublimeLinter/SublimeLinter/blob/8b46320aca3d61bc76f88b315e1f1cab78c548f1/lint/settings.py#L152-L154

--- 

https://github.com/SublimeLinter/SublimeLinter/blob/8b46320aca3d61bc76f88b315e1f1cab78c548f1/lint/settings.py#L114-L128

These are global settings, not *view* settings. Don't know why we're not just using `load_settings` here.

**Comment by kaste** [comment]
Ahem

https://github.com/SublimeLinter/SublimeLinter/blob/8b46320aca3d61bc76f88b315e1f1cab78c548f1/lint/settings.py#L150

**Comment by FichteFoll** [comment]
Since settings are merged with project-specific stuff, we need to re-evaluate all settings for each lint and using an on-change listener doesn't help much, unless we added a complex caching mechanism which I don't think we need.

It would be nice to be able to disable linters and otherwise specify settings for a view specifically (see also #244), though I believe this should be tackled separately.
