### ISSUE TITLE
About going live with SL4

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#893]
Another call for opinion here. @kaste @pykong @FichteFoll as the main collaborators the past month or so.

The [milestone](https://github.com/SublimeLinter/SublimeLinter/milestone/2) is done, apart from one problem that probably doesn't exist. We've been at about 4 pull requests per day average for the past week, but I think it may be slowing down. Also, even if it doesn't I don't expect to hit many things that will change user land stuff like settings. Dropping SL4 should by no means put a hold to anyone who wants to refactor and improve the internals, but it seems our feature set is pretty solid at this point. 

At least, in my opinion. I have been wrong before 😄 

So, how do you guys feel about it.

- Do we need more time for testing ourselves?
- Does anyone want to get a feature or refactor in before we go (e.g. I'd like to land #887)?
- Is there anything we think is not good about the upgrade process that we should fix?

Personally, I don't look forward to hitting hundreds, or perhaps thousands of users, with the update and having to deal with the flood of people not reading the docs or otherwise unable to deal with the changes to settings and UI. 

We tried upgrading settings, but that's pretty hard to to do well. At that time I didn't think it was worth the effort to try to get it to work (it was various kinds of broken), but someone may want to revisit. 

Perhaps we should put a message out that it's going to happen soon and prepare people about what's going to happen. Perhaps even tell them block the upgrade via `auto_upgrade_ignore` in PC, if they really don't want to upgrade (or simply don't have the time for it now). So, that's something I'm thinking I should do first. 

Anything else?

**Comment by pykong** [comment]
Going **live**? What did I miss? As I remember you wanted the beta to last several months.

**Comment by braver** [comment]
You know what. I’ve been putting issues and pull requests in the 4.0.0 milestone if I really wanted them to be solved before dropping the release. I am definitely ok with you guys doing that now, especially as we’re moving towards more refactoring and other work on internals. As long as it’s realistic that we’ll get it done it’s fine, and then we can discuss our progress towards that milestone.

**Comment by kaste** [comment]
Ship it 👍 rather today than tomorrow. 

Why? 

- We still get bug reports for SL3. And I have almost zero knowledge about SL3 anymore. We resolved a *lot* of bugs. The only thing we now do is point them to try the beta. 

- A somewhat detached master from the product just doesn't work. 3 months without real user feedback is already nuts.

What I still want.

- E.g. deprecate/remove `config_file` if feasible (bc it would be a breaking change)
- Ship a sublime_linter.version so plugin authors can program against two different API's. !!!
- Visible user feedback on config errors, e.g. via the toasts. That's one of the things people say VSCode is so good at. Just bc they prompt you with a `Could not find eslint`. We can toast a message, or open an error panel. (As I said in #885 I was actually surprised about the good look of this first implementation.) Right now we don't even flash the status bar. 

Since we know, that SL4 is breaking, we must inform users how to opt-out of automatic updates, or ideally how to roll back. Bc otherwise it just nulls your complete Monday.

**Comment by braver** [comment]
> 3 months without real user feedback is already nuts.

That's a truth. And a big reason I want to move towards 🛥 

> Ship a sublime_linter.version so plugin authors can program against two different API's. !!!

They can read `util.get_sl_version` and parse the string. It's guaranteed to be a semver string because package control works that way. Is that good enough or do you envision something else?

> Visible user feedback on config errors

I use gitsavvy a lot and it uses the output panel on errors. It's a great solution because it's visually very apparent that something happened, it sticks around so I have the time to read it, and it has enough space to actually tell me something useful. I also like it because it's an existing ST UI pattern. We flash settings errors on the statusbar, we should open a panel for that too. 

> we must inform users how to opt-out of automatic updates

Will do, am on it.

**Comment by FichteFoll** [comment]
I'm mostly with you, but don't want to type out the details on mobile. Will try to remember at a later point.

**Comment by kaste** [comment]
> They can read util.get_sl_version and parse the string. 

If that's only avail in SL4, then users would actually have to do `if hasattr(util, 'get_sl_version')`. 

If it's a semver string. We could cheap parse: `tuple(semversionstring.split('.'))`.

What is the better return value to refer to the master/edge. Currently it returns 'unknown', although if it's master we know it is at least `(4, 'master')`.

**Comment by braver** [comment]
Ok, let’s spin that discussion off into a separate issue.

**Comment by FichteFoll** [comment]
I'm still keen on getting *Scope based syntax detection* through with SL4 because this is a huge change and I'd rather not lose out on the chance of doing it in this major release. I'll try to thing of something in the next couple days and already have a couple ideas, but let's keep that to the respective issue(s).

Personally, I haven't been using SL too much over the recent weeks and when I did, I always found something that wasn't working right or optimally. It never broke down completely, but I'd rather have at least a week of testing period once we believe we are feature complete and the refactoring PRs have settled.

>We still get bug reports for SL3. And I have almost zero knowledge about SL3 anymore. We resolved a lot of bugs. The only thing we now do is point them to try the beta.

Imo this is fine. If things are broken in SL3, suggest to use SL4. If it's still broken there, fix it. It's not worth spending any effort at all on SL3 at this point.

**Comment by braver** [comment]
Good enough for now. We'll work on refinements for a while yet, there is no hurry. People can track the milestone to see what's planned before dropping 4.
