### ISSUE TITLE
Method for removing unused errors.

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#900]
After merging #898, errors are based solely on `buffer_id`. This necessitates a new way to remove unused errors.

Quoting @kaste:
> We need to add some logic to remove bid from errors when it's not used anymore.

> This can be tricky. Generally we can multiple views into the same buffer. So we can remove only if this view here is the last one. But one has to check/test how we can iterate here over window.views() for example. Is this view here still in window.views(). What if the user closes the window?

**Comment by braver** [comment]
Just so I understand the issue here. We store errors per buffer. We don't clean them up (unless the syntax map changes). So if you have a long session with a lot of views and a lot of errors, the error store grows and it can be a bit of a memory leak.

The solution seems to be:

- assuming `on_pre_close` is triggered on the view if a window closes
- in `on_pre_close` of a view
- loop over all views in all windows to make a list of buffer_id's
- if the the buffer_id of this view has one entry in that list (ie. we're closing the last one)
- then remove the errors for said buffer_id

**Comment by kaste** [comment]
Basically yes, we just need to figure how Sublime works here. `on_pre_close`fires when the view gets closed and when the user closes the window. 

And we just have to figure, what the iterators Sublime provides (`windows()`, `views()`) give us in those scenarios.
