### ISSUE TITLE
Navigating to error with keyboard no longer shows popup

### ISSUE THREAD

**Issue by anderssvendal** [SublimeLinter/SublimeLinter#920]
Been using SublimeLinter for a long time, and it's by far my favourite ST plugin! I recently upgraded to SL4 beta and for the most part loving the new version 😄 

One feature from SL3 I'm missing is navigating to a  line with one or more errors and have them displayed in a tooltip/popup. With SL4 I have to move the mouse cursor over the error or the icon in the gutter. Any plans to bring the old functionality back?

**Comment by braver** [comment]
You can trigger the "show line errors" (`sublime_linter_line_report`) command via a keybinding (it's not working for me at the moment, am looking into that... it's a beta). That will show you all the errors on the line. If your cursor is at a specific error, the statusbar will display that error. Additionally you can open the output panel ("show all errors") and it will highlight the error at your cursor. 

So, there should be some alternatives to suit the same purpose. We have no intention to bring back the tooltip that sticks to your cursor because it's crazy annoying and conflicts with other features like auto-complete. I hope this works for you?

**Comment by anderssvendal** [comment]
The keybinding is working on my machine😄 I get that the old behaviour can be annoying, so `sublime_linter_line_report` should work. Thanks for the tip and the super fast reply!

**Comment by braver** [comment]
Cool 👍

**Comment by kaste** [comment]
I'll probably do a plugin here.
