### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#930]
Goals:

- [x] No interleaved printing in a multi-threaded environment
- [x] Associate a log line with the caller context which is the thread, the file, and its line 
- [x] Configurable, so we can have more or less noise in the console. The default for our current `debug: true` would probably be 'INFO', for `debug: false` it would still be either 'ERROR' or 'WARNING'
- [x] Maybe a hook ('Handler') that wires up 'ERROR' messages with a toast plugin or an (yet to come) error panel, or a just status bar message to keep it simple 🌶 
- [x] If the user says `debug: false` (the current default) we do not format the messages fancy with thread, filename, line; we just print the actual *message* 🎆 
- [x] A plugin author justs import the std python *logging* library and inits it to e.g. `getLogger('SublimeLinter.flake8')` and then logs away, and it will cooperate with our Logger. T.i. the author will not use `persist.debug` anymore ❤️ 

Related #909

**Comment by FichteFoll** [comment]
If the default for `debug` is supposed to be 'INFO', where does 'DEBUG' come in?
In my packages, I allow configuring the level pretty directly through the settings. No need to abstract over that imho.

https://github.com/SublimeText/PackageDev/blob/cdc6d33f6de672d577790f87e9fb207bd7b23131/Package/PackageDev.sublime-settings#L2-L4

And I actually think that the best default for SublimeLinter currently would be INFO, since there is quite some useful information there such as the extracted PATH from the user's shell or similar.

Like the idea for having a handler to fire toast messages (if implemented).

**Comment by braver** [comment]
I think noise control is a bit much here. End users will not want to have anything printed except serious errors, or debug info to help with configurations (i.e. "on" or "off"). Developers will want fine grained control, i.e. logging of the thing they're working on in addition to the errors. 

I think 1 and 2

**Comment by braver** [comment]
Sorry, wrong button

**Comment by kaste** [comment]
3 is a builtin functionality of the std logging library. We must translate our *true|false* to the appropriate so-called log levels. But then we also accept `debug: 'debug'` bc that's the name of such a level. Reducing that functionality would be more work than utilizing it.

**Comment by braver** [comment]
👍🏻 

So, DEBUG equals INFO then.

**Comment by kaste** [comment]
Added two more goals. 

@FichteFoll Regarding #909 I'm against `self.logger` and its machinery. I don't think the refactoring (getting rid of `linter.name` injection) itself can be a goal here. What is important, when we have crazy interleaved results, is that we have a thread `ident` in the log (which is really more than the (linter_name, file_name) tuple, it's an id. On the other hand, we can of course give our threads good names and just log them. Generally pythons `logging` is already a thread-aware, global machinery. So we need a really good reason for **self**.logger. We usually just call logger.debug(). 

The naming of the threads can be done in the backend. Since we already group by linters, we could name the threads (linter_name, file_name). And python will add a counter (`_1` etc.) to that.

**Comment by FichteFoll** [comment]
Leaving out self.name for next logging wasn't the goal, it was just a side product.

The thread's name could easily be assigned by the backend and there is even a field in log records for this, so we'd only need to change the format.

I'm indifferent about self.logger vs logging.debug, but what about the class-specific logger? Do you want a thread-global logger for that as well? I'm not familiar with the logger selection stuff and when exactly classmethods are called.

**Comment by FichteFoll** [comment]
I was trying to draft a checklist of things I need to address in #909 to get us closer to the items specified in the checklist (without doing all of them, since I believe those should be then added later in separate PRs), however, I still have a couple questions.

>- Associate a log line with the caller context which is the thread, the file, and its line

We don't have the line in `Linter.lint`, just the code. I think the easiest way would be to apply the context manager in `backend.execute_lint_task`. That way we ensure the logger is active even when a plugin overrides `Linter.lint`. Two currently do, contrib-julialintserver and contrib-verilator.

>- Configurable, so we can have more or less noise in the console. The default for our current debug: true would probably be 'INFO', for debug: false it would still be either 'ERROR' or 'WARNING'
>- If the user says debug: false (the current default) we do not format the messages fancy with thread, filename, line; we just print the actual message 🎆

So you're saying by default only warnings and errors should be printed but without any context information as to which linter or file they happened with? Sounds unnecessarily obscure. We don't need to actively *hide* this information from users, do we?

A comment on the `debug: true/false` => `DEBUG`/`INFO`/`WARNING` mapping would be nice, too. Currently, I map true to DEBUG and false to INFO. You might want to skip over the changes in #909 to get a better picture of when I use which level (and if I use them incorrectly in your opinion). We could also add direct log level control and treat the boolean as a backwards-compatible fallback.

>- A plugin author justs import the std python logging library and inits it to e.g. getLogger('SublimeLinter.flake8') and then logs away, and it will cooperate with our Logger. T.i. the author will not use persist.debug anymore ❤️

Technically, they should just be using `from SublimeLinter.lint import logging` and then `logging.*` directly, according to your comments. They shouldn't need to create get a logger on their own as the appropriate one would be active anyway, unless they do really obscure stuff, in which case the default logger (`SublimeLinter`) will kick in.

**Comment by kaste** [comment]
As a quick reply. I don't want a context manager, or different loggers, maybe per linter. Also I would like that we just import logging; logger = logging.getLogger() per module and then use that standard logger. 

The same would apply for plugin authors. They import the std library and instantiate a logger in the standard way.

**Comment by FichteFoll** [comment]
What about the context information about the "active" linter and view? That would be lost with a module-global logger, unless the information was added to *every log event* manually.

**Comment by kaste** [comment]
This 'context' information can be encoded in the thread. Note that `(linter_name, file_name)` is not sufficient here bc we can have multiple tasks per `linter, file` group. (E.g. the annotation plugin produces a lot of tasks.)

So, we basically need the thread (its id or its name) to tell them apart. 

Now, I'm not a friend of long monotonous log lines, but that's a thing for the formatter.

```
[SublimeLinter] (flake8) (backend.py)_1 util.py:156: Detected syntax: python
[SublimeLinter] (flake8) (backend.py)_1 util.py:156: wanted python is 'None'
```

Maybe it would look nice if we do

```
[SublimeLinter] #1 linter.py:156: 'flake8' is linting 'backend.py'
[SublimeLinter] #1 linter.py:178: wanted python is 'None'
[SublimeLinter] #2 linter.py:156: 'flake8' is linting 'util.py'
```

where `#1` is the monotonous increasing task number.

Now, that's to decide later. A nice thing would be probably to have a smart Formatter. If I set the threadname to something meaningful (e.g. `LintTask #1`), it should print `#1`. Otherwise, it should not print it at all, bc the standard thread names are ugly.

**Comment by kaste** [comment]
If `debug: false` I would like a different log format bc we want to use the logging system to give normal user feedback. E.g.

```
[SublimeLinter] ERROR: You set 'executable' to '/foo/flake8' but this file does not exist.  .... 
You can find more about this here: https://blah.com/faq
```

or

```
[SL] NOTE: No local 'eslint' found. Did you 'npm install'?
```

**Comment by FichteFoll** [comment]
My main issue here is that we don't actually create a thread for each lint task (rightfully), so the thread would have to be renamed repeatedly, notably for annotations which creates many tasks. I mean, we could do that, but we'd also have to set the thread's name to the *verbatim* text we'd want to use for logging since we cannot modify that dynamically as we just use `%(thread)s` in the format, and when we need to declare the format beforehand anyway, we might as well do it as I did and create the logger with the respective formatter directly.

For https://github.com/SublimeLinter/SublimeLinter/pull/909/files#diff-8120b617e4c6c91f43e1aec1ba391da7R680, which would you prefer?

```
[SublimeLinter] WARNING: wanted working_dir '/_tmp' is not a directory
[SublimeLinter] [flake8] WARNING: wanted working_dir '/_tmp' is not a directory
[SublimeLinter] flake8: WARNING: wanted working_dir '/_tmp' is not a directory
```

The first would be removing the context from log events, the second would be the current PR state, and the latter would require both removing the context and then readding the linter name manually to the message.

The thing is, we get the second option for free currently and I don't understand why you would remove that. Surely users would appreciate if they know which linter produced a warning or error, even if it can most likely be inferred from the executable's name, like if that can't be found.  However, in the message I presented there is no way to infer the linter's name from the message and you'd have to check all your linters' settings to see which one was errorneous.

**Comment by kaste** [comment]
Well, that seems to get trickier than I thought. Honestly, if we need to design the system around the concrete output format, that doesn't sound really compelling. The first constraint for me was that I want that dev user just uses the std library. So essentially we just use `logger.warning('...')` wherever we want and we have a system that makes a useful log message out of it if we're currently in the backend linting phase. Otherwise not, bc only the backend is multi-threaded and confusing.

So, my simple solution was

```
threading.current_thread().name = 'LintTask.{}.{}'.format(linter_name, file_base_name)  # probably set in Linter.lint, but could also be set in Thread(name='...')

# then everything else makes one of our Formatters and/or handlers; e.g.
# fmt = '[SL] ({linter_name} {file_base_name}) {filename}:{lineno}: {msg}'
	def format(self, record):
		thread_name = record.threadName 
		if thread_name.startswith('LintTask.'):
			_, linter_name, file_base_name = thread_name.split('.')
			record.linter_name = linter_name
			record.file_base_name = file_base_name
		#etc.pp
		return super().format(record)
```

And if we then hate the format, we just change it in the formatter. 

Now, the tricky part is how do we get a nice thread id. Bc the actual thread.get_ident() is ugly e.g. '15442', '7604'. I mean, these are really random numbers for the end user. So a beautiful, monotonic '#1', '#2', for each task would look nice.

**Comment by kaste** [comment]
ADD: The thread_id is not even unique bc I reuse the threads. I first thought, whenever we see a new ident we map it to nice monotonic counter. But, then, a shit, we reuse them. 

Ah well we could use the hit_time for that. The tuple (linter_name, view.id(), hit_time) is unique. 

```
counter = 1
@lru_cache()
def get_nice_id(linter_name, vid, hit_time):
	return counter++
```

**Comment by FichteFoll** [comment]
See my current changeset at my fork: https://github.com/FichteForks/SublimeLinter3/compare/logging_test_iteration.

A linter plugin would use this as follows:

```py
from SublimeLinter.lint import logging
from SublimeLinter.linter import Linter

class mylinter(Linter):
    def cmd(self):
        logging.debug("I'm determining the command to run")
        return ["mylinter"]
```

**Comment by kaste** [comment]
Ah well, @FichteFoll , that just doesn't work. 😕 You just hiding it. `logging.debug` is fake, it is actually `logging.getLogger().debug()` all the time. And if you hide it, you lose the filename and lineno.

**Comment by FichteFoll** [comment]
`logging.debug` is `logging.get_current_logger().debug`, where get_current_logger fetches the currently active logger on the thread as it has been set by `logging.logger_context`.

**Comment by kaste** [comment]
Yeah, but I meant the std library logging, I made that clear everywhere.

**Comment by FichteFoll** [comment]
Okay, so I believe our current problem is as follows:

You want all modules to have their own logger in standard `logging` stdlib fashion, but still automatically attach context information about the linter, filename and task id when there is any.

The only method to do this with the stdlib directly (i.e. without custom loggers) is to encode all the extra information in the thread's name so that the `%(threadName)s` field can be expanded to that. Verbatim, without modification, since there is no other way to automatically infer dynamic content.
We only want to change the thread names for threads we own though and not the main (async) thread, as they are shared.

Now, a different way would be to do what I chose, which is to wrap `logging.getLogger` calls with an artificial logger hierarchy and adding a handler with a specific formatter that statically contains the extra data and is updated whenever the context is entered (where otherwise the thread would be renamed). This does not affect shared state with other plugins since the created loggers are for to be accesse by SL only. However, plugins and modules must use our own methods to retrieve loggers instead of the stdlib.

And finally, a wrapper Logger class could be used that adds the `extra` kwarg to all logger calls, which is then inserted into the base template string. The advantage over option 2 would be that we don't need the Logger hierarchy anymore and just store a thread-specific state that we fetch the `extra` data from. A disadvantage is that the state needs to be translated into the `extra` mapping for each call, though that should be negligible. We also still need custom methods to retrieve the custom Logger wrapper classes.

Using any of the latter two options with `logging.setLoggerClass` is not an option because that affects all loggers created by all plugins.

**Comment by kaste** [comment]
Given the fact that I never used and configured the python logging library, I felt really insecure and doubtful after this last comment. I read it the day after, and then the day after that. 

#980 is the implementation I had in my mind. And it worked out pretty well, I think.

**Comment by FichteFoll** [comment]
Just FYI, I can only take a look at Monday or later.
