### ISSUE TITLE
Problems/questions for the highlights

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#939]
As a by-product of refactoring highlight.py (now highlights_view.py). 

1. We have the following filtering:

https://github.com/SublimeLinter/SublimeLinter/blob/fd6f8a8e9d8db3daf634044d27b52a7a5319baec/highlight_view.py#L90-L93

which basically means we *throw away errors* if we can't find a style. (Note I don't know anything about this *style* stuff per se. I just did the refactoring.) Generally, I don't think we should throw away errors, we don't even log here. So the question is, when exactly will we throw away errors? Can't we just rely on a fallback default to be always there? If we really need to discard an error, then we should log about it. Bc it will confuse users of course.

2. We have the following sort for the gutter icons:

https://github.com/SublimeLinter/SublimeLinter/blob/fd6f8a8e9d8db3daf634044d27b52a7a5319baec/highlight_view.py#L118-L121

Shouldn't this be rather `-e['priority'], e['error_type']`? T.i if two errors have the same priority, the 'ERROR' wins. So we could demote/promote errors freely.

Also: Why isn't this code parallel to the sorting for the underline/outline highlights:

https://github.com/SublimeLinter/SublimeLinter/blob/fd6f8a8e9d8db3daf634044d27b52a7a5319baec/highlight_view.py#L134-L138

Here we just take the first 'ERROR' not looking at the priority at all.

**Comment by braver** [comment]
I can only tell you something about 1. This may be an old guard against invalid settings, I don’t think we update styles internally if they’re invalid. 

So that’s one reason to not throw away stuff, but perhaps it’s just defensive in the cheapest way possible. 

We have valid default styles we can always fall back on though. So, if we do it right we never have to fall back, but if we do we should fall back to the defaults instead of removing the errors.
